<?php

$distanciaEstilo = $this->viewData->distanciaEstilo;
$torneios = $this->viewData->torneios;
$categorias = $this->viewData->categorias;
$provas = $this->viewData->provas;

?>

<main>
    <section class="py-5 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto mb-4 mb-sm-0">
                <h1 class="fw-light">Provas</h1>
            </div>
        </div>
        <div class="d-none d-sm-flex justify-content-end">
            <a class="w-25 btn btn-primary btn-lg" id="errorModal" href="/add_prova">Adicionar</a>
        </div>
        <div class="d-flex d-sm-none justify-content-end">
            <a class="w-100 btn btn-primary btn-lg" id="errorModal" href="/add_prova">Adicionar</a>
        </div>
    </section>


    <?php $countLists = 1;
    foreach ($torneios as $torneio) { ?>
        <div class="d-flex justify-content-between">
            <p class="lead"><?php echo $torneio['nomeTorneio'] . ' - ' . implode('/',  array_reverse(explode('-', $torneio['dataTorneio']))) ?></p>
            <button type="button" class="btn btn-primary" style="min-width: 100px; height: 40px;" data-bs-toggle="collapse" data-bs-target="#table<?= $countLists ?>" aria-expanded="false" aria-controls="collapseExample">Ver mais</button>
        </div>
        <table class="table w-75 mx-auto collapse" id="table<?php echo $countLists ?>">
            <thead>
                <tr>
                    <th scope="col">Prova</th>
                    <th scope="col">Estilo</th>
                    <th scope="col">Genero</th>
                    <th scope="col">Categorias</th>
                </tr>
            </thead>
            <?php
            foreach ($provas as $prova) { ?>
                <?php if ($prova['id_torneio'] == $torneio['IDTORNEIO']) { ?>
                    <tbody>
                        <tr>
                            <td><?= 'Prova numero ' . $prova['numeroProva'] ?></td>
                            <td><?= $prova['distancia'] . 'm ' . $prova['nomeEstilo'] ?></td>
                            <td><?= $prova['genero'] ?></td>
                            <td><?php if ($prova['categoriaMinima'] != $prova['categoriaMaxima']) { ?>
                            <td><?= $prova['categoriaMinima'] . ' a ' . $prova['categoriaMaxima'] ?></td>
                        <?php } else { ?>
                            <td><?= $prova['categoriaMinima'] ?></td>
                        <?php } ?>
                        </tr>
                    </tbody>
                <?php } ?>
            <?php } ?>
        </table>
        <hr>
    <?php $countLists++;
    } ?>
</main>

<script>

</script>
