<?php
$piscinas = $this->viewData->piscinas;
$complexos = $this->viewData->complexos;
$federacoes = $this->viewData->federacoes;
$torneio = $this->viewData->torneio;

?>

<main>
    <section class="py-5 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
                <h1 class="fw-light">Edição de Torneios</h1>
            </div>
        </div>
        <p class="lead">Alterar dados do torneio</p>
    </section>

    <?php if (isset($_GET['error']) && $_GET['error'] == '3') {
        echo '<div class="alert alert-danger" role="alert">
                Nome já cadastrado
                </div>';
    } elseif (isset($_GET['error']) && $_GET['error'] == '4') {
        echo '<div class="alert alert-danger" role="alert">
                Sigla já cadastrada
                </div>';
    } ?>

    <div class="row g-5">

        <div class="">
            <h4 class="mb-3"></h4>
            <form action="update_torneio" class="needs-validation" method="post" enctype="multipart/form-data">
                <input type="hidden" name="idtorneio" value="<?= $torneio['IDTORNEIO'] ?>">
                <div class="row g-2">
                    <div class="col-md-12">
                        <label for="nomeTorneio" class="form-label">Nome Torneio</label>
                        <?php if (isset($_GET['error']) && $_GET['error'] == '1') {
                            echo '<div class="alert alert-danger" role="alert">
                                        Campo Obrigatório
                                        </div>';
                        } ?>
                        <input type="text" class="form-control" id="nomeTorneio" placeholder="Nome" name="nomeTorneio" value="<?= $torneio['nomeTorneio'] ?>" required>
                    </div>
                </div>

                <div class="row g-2">
                    <div class="col-md-2">
                        <label for="dataTorneio" class="form-label">Data Início</label>
                        <input type="date" class="form-control" id="dataTorneio" placeholder="Apelido" name="dataTorneio" value="<?= $torneio['dataTorneio'] ?>" required>
                    </div>
                    <div class="col-md-2">
                        <label for="dataFimTorneio" class="form-label">Data Fim</label>
                        <input type="date" class="form-control" id="dataFimTorneio" placeholder="Apelido" name="dataFimTorneio" value="<?= $torneio['dataFimTorneio'] ?>" required>
                    </div>
                    <div class="col-md-8">
                        <label for="federacao" class="form-label">Federação</label>
                        <select name="id_federacao" class="form-select" id="federacao">
                            <option value="">Selecione</option>
                            <?php foreach ($federacoes as $federacao) { ?>
                                <option value="<?= $federacao['IDFEDERACAO'] ?>" <?php echo ($federacao['IDFEDERACAO'] == $torneio['ID_FEDERACAO']) ? 'selected' : '' ?>><?= $federacao['nomeFantasiaFederacao'] . ' - ' . $federacao['nomeFederacao']  ?></option>
                            <?php } ?>
                        </select>
                    </div>
                </div>

                <div class="row g-3">
                    <div class="col-md-8">
                        <label for="complexo" class="form-label">Local</label>
                        <select name="id_complexo" class="form-select" id="complexo">
                            <option value="">Selecione</option>
                            <?php foreach ($complexos as $complexo) { ?>
                                <option value="<?= $complexo['IDCOMPLEXO'] ?>" <?php echo ($complexo['IDCOMPLEXO'] == $torneio['ID_COMPLEXO']) ? 'selected' : '' ?>><?= $complexo['nomeFantasiaComplexo'] ?></option>
                            <?php } ?>
                        </select>
                    </div>
                    <div class="col-md-4">
                        <label for="piscina" class="form-label">Piscina</label>
                        <select name="id_piscina" class="form-select" id="piscina">
                            <option value="">Selecione</option>
                            <?php foreach ($piscinas as $piscina) { ?>
                                <option value="<?= $piscina['IDPISCINA'] ?>" <?php echo ($piscina['IDPISCINA'] == $torneio['ID_PISCINA']) ? 'selected' : '' ?>><?= $piscina['tamanhoPiscina'] . ' m' ?></option>
                            <?php }; ?>
                        </select>
                    </div>
                </div>

                <hr class="my-4">
                <div class="d-flex justify-content-around">

                    <button class="w-25 btn btn-primary btn-lg" type="submit">Alterar</button>
                    <a href="/list_torneios" class="w-25 btn btn-secondary btn-lg">Voltar</a>
                </div>
            </form>
        </div>
    </div>
</main>
