<main>
    <section class="py-5 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
                <h1 class="fw-light">Torneios</h1>
            </div>
        </div>
        <div class="d-flex justify-content-end mb-5">
            <a class="w-25 btn btn-primary btn-lg" id="errorModal" href="/add_torneio">Adicionar</a>
        </div>
    </section>
    <?php foreach ($this->viewData->torneios as $torneio) { ?>
        <div class="col-md-10">
            <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                <img class="col-2 d-none d-lg-block mt-3 object-fit-contain" src="<?= $torneio['logoFederacao'] ?>" alt="">
                <div class="col p-4 d-flex flex-column position-static">
                    <strong class="d-inline-block mb-2 text-primary-emphasis"><?= $torneio['nomeFantasiaFederacao'] ?></strong>
                    <h3 class="display-6 mb-0"><?= $torneio['nomeTorneio'] ?></h3>
                    <div class="mb-1 text-body-secondary"><?php echo implode('/',  array_reverse(explode('-', $torneio['dataTorneio']))); ?><?php if ($torneio['dataFimTorneio'] != '' && $torneio['dataFimTorneio'] != $torneio['dataTorneio']) {
                                                                                                                                                echo ' a ' .  implode('/',  array_reverse(explode('-', $torneio['dataFimTorneio'])));
                                                                                                                                            } ?></div>
                    <p class="lead card-text mb-1"><?= $torneio['nomeFantasiaComplexo'] ?></p>
                    <p class="card-text mb-auto "><em><?= 'Piscina: ' . $torneio['tamanhoPiscina'] . 'm' ?></em></p>
                    <a href="view_torneio?id=<?= $torneio['IDTORNEIO'] ?>" class="btn btn-secondary ">
                        Ir para torneio
                    </a>
                </div>
                <div class="col-auto d-none d-lg-block">
                    <rect width="100%" height="100%" fill="" />
                    <img src="<?= $torneio['fotoComplexo'] ?>" alt="" width="350" height="250">
                </div>
            </div>
        </div>
    <?php } ?>
</main>
