<?php

$torneio = $this->viewData->torneios;
$provas = $this->viewData->provas;


//print_r($provas);

?>

<div class="container">
    <main>
        <div class="d-flex align-items-start mb-5">
            <img src="<?= $torneio['logoFederacao'] ?>" class="img-logo-fill" alt="">
            <div class="text-center">
                <h2 class="display-5 my-3"><?= $torneio['nomeTorneio'] ?></h2>
                <p class="lead"><?php echo implode('/',  array_reverse(explode('-', $torneio['dataTorneio']))); ?><?php if ($torneio['dataFimTorneio'] != '' && $torneio['dataFimTorneio'] != $torneio['dataTorneio']) {
                                                                                                                        echo ' a ' .  implode('/',  array_reverse(explode('-', $torneio['dataFimTorneio'])));
                                                                                                                    } ?></p>
            </div>
        </div>

        <div class="d-flex justify-content-between row g-5">

            <div class="row g-3">
                <input type="hidden" name="idcomplexo" value="<?= $complexo['IDCOMPLEXO'] ?>">
            </div>
            <div class="col-md-7 col-lg-8 ">
                <div class="mb-3">
                    <img class="img-big img-fluid" src="<?= $torneio['fotoComplexo'] ?>" alt="">
                </div>
            </div>
            <div class="col-md-5 mt-6 col-lg-4 views-data">
                <p class="lead">Endereço:</p>
                <p class=""><?= $torneio['enderecoComplexo'] ?></p>
                <p class=""><?= $torneio['bairroComplexo'] ?></p>
                <p class=""><?= $torneio['cidadeComplexo'] ?> - <?= $torneio['siglaEstado'] ?></p>
            </div>
        </div>

        <table class="table">
            <thead>
                <tr>
                    <th class="">Prova</th>
                    <th class="">Estilo</th>
                    <th class="">Genero</th>
                    <th class="">Categorias</th>
                </tr>
            </thead>

            <?php
            foreach ($provas as $prova) { ?>
                <tbody>
                    <tr>
                        <td><?= $prova['numeroProva'] ?></td>
                        <td><?= $prova['distancia'] . 'm ' . $prova['nomeEstilo'] ?></td>
                        <td><?= $prova['genero'] ?></td>
                        <?php if ($prova['categoriaMinima'] != $prova['categoriaMaxima']) { ?>
                            <td><?= $prova['categoriaMinima'] . ' a ' . $prova['categoriaMaxima'] ?></td>
                        <?php } else { ?>
                            <td><?= $prova['categoriaMinima'] ?></td>
                        <?php } ?>
                    </tr>
                </tbody>
            <?php } ?>

        </table>

        <div>
            <a href="/list_torneios" class="btn btn-success">Voltar</a>
        </div>

    </main>
</div>
