<main class="form-signin w-100 m-auto">

    <img class="mb-4" src="./images/swim_icon.png" alt="" width="72" height="57">

    <div class="text-center">
        <h1 class="h3 mb-5 fw-normal">Erro</h1>
        <div class="alert alert-danger ">
            <p><?= $this->setHtmlData->error ?></p>
        </div>


        <a class="btn btn-primary w-100 py-2 mt-3" href="<?= $this->setHtmlData->url ?>">Voltar</a>
        <p class="mt-5 mb-3 text-body-secondary">&copy; 2017–2024</p>
</main>
