<main class="form-signin w-100 m-auto">
  <form method="post" action="/authenticate">
    <img class="mb-4" src="./images/swim_icon.png" alt="" width="72" height="57">
    <h1 class="h3 mb-3 fw-normal">Please sign in</h1>
    <?php if (isset($_GET['login']) && $_GET['login'] == 'erro') { ?>
      <div class="alert alert-danger">
        <p>Digite um usuário e senha validos</p>
      </div>
    <?php } ?>
    <div class="form-floating">
      <input type="text" class="form-control" id="floatingInput" name="username" placeholder="name@example.com">
      <label for="floatingInput">Email address</label>
    </div>
    <div class="form-floating">
      <input type="password" class="form-control" id="floatingPassword" name="passwd" placeholder="Password">
      <label for="floatingPassword">Password</label>
    </div>

    <!-- <div class="form-check text-start my-3">
      <input class="form-check-input" type="checkbox" value="remember-me" id="flexCheckDefault">
      <label class="form-check-label" for="flexCheckDefault">
        Remember me
      </label>
    </div> -->
    <button class="btn btn-primary w-100 py-2" type="submit">Entrar</button>
  </form>
  <a class="btn btn-primary w-100 py-2 mt-3" href="register">Não tenho cadastro</a>
  <p class="mt-5 mb-3 text-body-secondary">&copy; 2017–2024</p>
</main>