<?php
$complexo = $this->viewData->complexo;
?>

<div class="container">
    <main>
        <div class="py-5 text-center">
            <h2 class="display-5 my-3">Cadastro de Piscinas e Complexos de Natação</h2>
            <p class="lead">Editar piscina</p>
        </div>
        <?php if (isset($_GET['error']) && $_GET['error'] == '3') {
            echo '<div class="alert alert-danger" role="alert">
                Nome já cadastrado
                </div>';
        } elseif (isset($_GET['error']) && $_GET['error'] == '4') {
            echo '<div class="alert alert-danger" role="alert">
                Sigla já cadastrada
                </div>';
        } ?>

        <div class="row g-5">
            <div class="col-md-5 col-lg-4 order-md-last">
                <div class="d-flex justify-content-center align-items-center mb-3">
                    <img class="img-logo-border" src="<?= $complexo['fotoComplexo'] ?>" alt="">
                </div>

            </div>
            <div class="col-md-7 col-lg-8">
                <h4 class="mb-3"></h4>
                <form action="update_complexo" class="needs-validation" method="post" enctype="multipart/form-data">
                    <input type="hidden" name="idcomplexo" value="<?= $complexo['IDCOMPLEXO'] ?>">
                    <div class="row g-3">
                        <div class="col-12">
                            <label for="nomeComplexo" class="form-label">Nome</label>
                            <?php if (isset($_GET['error']) && $_GET['error'] == '1') {
                                echo '<div class="alert alert-danger" role="alert">
                                            Campo Obrigatório
                                      </div>';
                            } ?>
                            <input type="text" class="form-control" id="nomeComplexo" placeholder="Nome" name="nomeComplexo" value="<?= $complexo['nomeComplexo'] ?>">
                            <div class="invalid-feedback">
                                Valid first name is required.
                            </div>
                        </div>
                        <div class="col-12">
                            <label for="nomeFantasiaComplexo" class="form-label">Nome Fantasia</label>
                            <input type="text" class="form-control" id="nomeFantasiaComplexo" placeholder="Nome Piscina" name="nomeFantasiaComplexo" value="<?= $complexo['nomeFantasiaComplexo'] ?>">
                        </div>
                    </div>

                    <div class="col-12">
                        <label for="enderecoComplexo" class="form-label">Endereço</label>
                        <input type="text" class="form-control" id="enderecoComplexo" placeholder="Endereço" name="enderecoComplexo" value="<?= $complexo['enderecoComplexo'] ?>">
                    </div>

                    <div class="col-12">
                        <label for="bairroComplexo" class="form-label">Bairro</label>
                        <input type="text" class="form-control" id="bairroComplexo" placeholder="Bairro" name="bairroComplexo" value="<?= $complexo['bairroComplexo'] ?>">
                    </div>
                    <div class="row g-3">
                        <div class="col-6">
                            <label for="cidadeComplexo" class="form-label">Cidade<span class="text-body-secondary">(Opcional)</span></label>
                            <input type="text" class="form-control" id="cidadeComplexo" placeholder="Cidade" name="cidadeComplexo" value="<?= $complexo['cidadeComplexo'] ?>">
                        </div>
                            <label for="estado" class="form-label">Estado</label>
                            <select name="id_estado" class="form-select" id="estado">
                                <option value="">Selecione</option>
                                <?php foreach ($this->viewData->estados as $estado) { ?>
                                    <option value="<?= $estado['IDESTADO'] ?>" <?php if ($estado['IDESTADO'] == $complexo['ID_ESTADO']) {
                                        echo 'selected';
                                    }  ?>><?= $estado['nomeEstado'] . ' - ' . $estado['siglaEstado'] ?></option>
                                <?php } ?>
                            </select>
                        </div>
                        <div class="col-12">
                            <label for="observacaoComplexo" class="form-label">Observação<span class="text-body-secondary">(Opcional)</span></label>
                            <textarea type="text" class="form-control" id="observacaoComplexo" placeholder="Texto livre" name="observacaoComplexo" value=""><?= $complexo['observacaoComplexo'] ?></textarea>
                        </div>
                    </div>
                    <div class="row gy-3">
                        <div class="col-md-6">
                            <label for="fotoComplexo" class="form-label">Foto</label>
                            <input type="file" class="form-control" id="fotoComplexo" aria-describedby="inputGroupFileAddon04" aria-label="Upload" name="fotoComplexo" accept="image/jpeg,.gif,.png" value="<?= $complexo['fotoComplexo'] ?>">
                            <input type="hidden" name="fotoAntiga" value="<?= $complexo['fotoComplexo'] ?>">
                        </div>
                    </div>
                    <hr class="my-4">
                    <button class="w-100 btn btn-primary btn-lg" type="submit">Editar</button>
                </form>
            </div>
        </div>
    </main>
