<?php
$complexo = $this->viewData->complexo;
?>

<div class="container">
    <main>
        <div class="py-5 text-center">
            <h2 class="display-5 my-3"><?= $complexo['nomeComplexo'] ?></h2>
            <p class="lead"><?= $complexo['nomeFantasiaComplexo'] ?></p>
        </div>

        <div class="d-flex justify-content-between row g-5">
            
            <div class="row g-3">
                    <input type="hidden" name="idcomplexo" value="<?= $complexo['IDCOMPLEXO'] ?>">
            </div>
            <div class="col-md-7 col-lg-8 ">
                <div class="mb-3">
                    <img class="img-big img-fluid" src="<?= $complexo['fotoComplexo'] ?>" alt="">
                </div>
            </div>
            <div class="col-md-5 mt-6 col-lg-4 views-data">
                <p class="lead">Endereço:</p>
                <p class=""><?= $complexo['enderecoComplexo'] ?></p>
                <p class=""><?= $complexo['bairroComplexo'] ?></p>
                <p class=""><?= $complexo['cidadeComplexo'] ?> - <?= $complexo['siglaEstado'] ?></p>
            </div>
            
            <div class="col-md-12 mt-5 col-lg-12">
                <p class="views-text"><?= $complexo['observacaoComplexo'] ?></p>
            </div>
        </div>
    </main>
</div>
