<?php
$estados = $this->viewData->estados;
?>

<div class="container">
    <main>
        <div class="py-5 text-center">
            <h2>Dados da Federacao</h2>
            <p class="lead">Incluir federação</p>
        </div>

        <div class="row g-5">
            <div class="col-md-5 col-lg-4 order-md-last">
                <div class="d-flex justify-content-center align-items-center mb-3">
                    <img class="img-logo" src="" class="img-foto" alt="">
                </div>
            </div>
            <div class="col-md-7 col-lg-8">
                <h4 class="mb-3"></h4>
                <form action="/save_federacao" method="POST" enctype="multipart/form-data" class="needs-validation">
                    <div class="row g-3">
                        <div class="col-12">
                            <label for="nomeFederacao" class="form-label">Nome</label>
                            <input type="text" class="form-control" id="nomeFederacao" placeholder="Nome da Federação" name="nomeFederacao" value="" required>
                        </div>
                        <div class="col-12">
                            <label for="nomeFantasiaFederacao" class="form-label">Sigla</label>
                            <input type="text" class="form-control" id="nomeFantasiaFederacao" placeholder="Sigla" name="nomeFantasiaFederacao" value="">
                        </div>
                    </div>

                    <div class="col-12">
                        <label for="emailFederacao" class="form-label">Email</label>
                        <input type="email" class="form-control" id="emailFederacao" placeholder="you@example.com" name="emailFederacao" value="">
                    </div>

                    <div class="col-12">
                        <label for="siteFederacao" class="form-label">Site</label>
                        <input type="text" class="form-control" id="siteFederacao" placeholder="www.example.com" name="siteFederacao" value="">

                    </div>
                    <div class="row g-3">
                        <div class="col-6">
                            <label for="facebookFederacao" class="form-label" name>Facebook <span class="text-body-secondary">(Opcional)</span></label>
                            <input type="text" class="form-control" id="facebookFederacao" name="facebookFederacao" placeholder="Link facebook" value="">
                        </div>
                        <div class="col-6">
                            <label for="instagramFederacao" class="form-label">Instagram <span class="text-body-secondary">(Opcional)</span></label>
                            <input type="text" class="form-control" id="instagramFederacao" name="instagramFederacao" placeholder="Link Instagram" value="">
                        </div>
                    </div>

                    <div class="col-md-5">
                        <label for="telefoneFederacao" class="form-label">Telefone<span class="text-body-secondary">(Opcional)</span></label>
                        <input type="text" class="form-control" id="telefoneFederacao" name="telefoneFederacao" placeholder="" value="">
                    </div>
                    <div class="row gy-3">
                        <div class="col-md-6">
                            <label for="logoFederacao" class="form-label">Logotipo</label>
                            <input type="file" class="form-control" id="logoFederacao" aria-describedby="inputGroupFileAddon04" aria-label="Upload" name="logoFederacao" accept="image/jpeg,.gif,.png" value="">
                            <input type="hidden" name="logoAntiga" value="">
                        </div>
                        <div class="col-md-6">
                            <label for="estado" class="form-label">Estado</label>
                            <select name="id_estado" class="form-select" id="estado" required>
                                <option value="">Selecione</option>
                                <?php foreach ($estados as $estado) { ?>
                                    <option value="<?= $estado['IDESTADO'] ?>"><?= $estado['nomeEstado'] ?></option>
                                <?php } ?>
                            </select>
                        </div>
                    </div>
                    <hr class="my-4">
                    <div class="grid column-gap-0">
                        <button class="w-25 btn btn-primary btn-lg disabled" type="submit" id="incluir">Incluir</button>
                        <a class="w-25 btn btn-secondary btn-lg" href="/federacao_admin">Voltar</a>
                    </div>
                </form>
            </div>
        </div>
    </main>
    <script>
        // Função de máscara para telefone
        let telefone = document.getElementById('telefoneFederacao');
        telefone.addEventListener('keypress', (event) => {
            if ((telefone.value).length < 16) {
                VMasker(telefone).maskPattern('(99) 9999 - 99999 ');
            } else {
                VMasker(telefone).maskPattern('(99) 99999 - 9999 ');
            }
        });
        // Função para liberar o botão de inclusão apenas após a seleção de estado
        let incluirBtn = document.getElementById('incluir');
        let estado = document.getElementById('estado');
        if(estado.value !== ''){
            incluirBtn.classList.remove('disabled');
        }
        estado.addEventListener('change', (e)=> {
            if(estado.value === '') {
                    incluirBtn.classList.add('disabled');
            } else {
                incluirBtn.classList.remove('disabled')
            }
            
        })
        
    </script>
