<?php

// print_r($this->viewData->federacoes);


?>

<main>

    <section class="py-5 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
                <h1 class="fw-light">Federações</h1>
            </div>
        </div>
    </section>

    <div class="album py-5 bg-body-tertiary">
        <div class="container">
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                <?php
                foreach ($this->viewData->federacoes as $federacao) { ?>
                    <div class="col">
                        <div class="card shadow-sm d-flex justify-content-between">
                            <img src="<?= $federacao['logoFederacao'] ?>" class="p-4 object-fit-contain" width="auto" height="300px" alt="Logotipo da <?= $federacao['nomeFantasiaFederacao'] ?>"></text>
                            <div class="card-body">
                                <h6 class="card-text"><?= $federacao['nomeFantasiaFederacao'] ?></h6>
                                <p class="card-text"><?= $federacao['nomeFederacao'] ?></p>
                                <div class="d-flex justify-content-between align-items-center">
                                    <div class="btn-group">
                                        <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                                        <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                                    </div>
                                    <small class="text-body-secondary"> <?= $federacao['nomeEstado'] ?> - <?= $federacao['siglaEstado'] ?></small>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php } ?>
            </div>
        </div>

</main>
