<?php

$atletas = $this->viewData->atletas;

// echo '<pre>';
// print_r($atletas);
// echo '</pre>';

?>

<div class="py-5 text-center">
    <h2 class="display-5 my-3">Administração de Atletas</h2>
    <!-- <p class="lead">Alteração dos dados</p> -->
</div>

<div class="text-end">
    <a href="insert_atleta">
        <i class="bi bi-plus-circle" style="font-size: 32px; color: rgba(var(--bs-secondary-color-rgb), 0.5)"></i>
    </a>
</div>

<div class="table-responsive">
    <table class="table text-center">
        <thead>
            <tr>
                <th style="width: 12%;">Dados</th>
                <th style="width: 12%;">ID</th>
                <th class="text-start" style="width: 12%;">
                    <div class="col-lg-12">
                        Nome
                        Sobrenome
                    </div>
                </th>
                <th class="text-start" style="width: 12%;">
                    <div class="col-lg-12">
                        e-mail /
                        Data Nasc
                    </div>
                </th>
                <th class="text-start" style="width: 12%;">Equipe</th>
                <th style="width: 18%;">CPF</th>

            </tr>
        </thead>
        <tbody>
            <?php foreach ($atletas as $atleta) { ?>
                <tr>
                    <td><a href="/index_atleta?id=<?= $atleta['IDATLETA'] ?>">
                            <img src="<?= $atleta['fotoAtleta'] ?>" class="img-foto" style="width: 60px; height: 60px; border:0 ">
                        </a>
                    </td>
                    <td><?= $atleta['IDATLETA'] ?></td>
                    <td class="text-start">
                        <?= $atleta['nomeAtleta'] ?>
                        <div class="col-lg-12">
                            <?= $atleta['sobreNomeAtleta'] ?>
                        </div>
                    </td>
                    <td style="font-size: small;" class="text-start"><?= $atleta['emailAtleta'] ?>
                        <div style="font-size: small;" class="col-lg-12">
                            <?php echo implode('/',  array_reverse(explode('-', $atleta['dataNascAtleta']))) ?>
                        </div>
                    </td>
                    <td style="font-size: small;"><?= $atleta['nomeEquipe'] ?></td>
                    <td><?= $atleta['cpfAtleta'] ?></td>
                    <td><a href="edit_atleta?id=<?= $atleta['IDATLETA'] ?>" class="btn btn-outline-primary">Editar</a></td>
                    <td><a href="delete_atleta?id=<?= $atleta['IDATLETA'] ?>" class="btn btn-outline-primary">Delete</a></td>
                </tr>
            <?php } ?>
        </tbody>
    </table>
</div>
