<?php
$atletas = $this->viewData->atletas;
?>

<div class="py-5 text-center">
    <h2 class="display-5 my-3">Administração de Atletas</h2>
</div>

<div class="text-end">
    <a href="/insert_atleta">
        <i class="bi bi-plus-circle" style="font-size: 32px; color: rgba(var(--bs-secondary-color-rgb), 0.5)"></i>
    </a>
</div>

<div class="table-responsive">
    <table class="table text-center">
        <thead>
            <tr>
                <th style="width: 12%;">Dados</th>
                <th style="width: 12%;">ID</th>
                <th class="text-start" style="width: 12%;">
                    <div class="col-lg-12">
                        Nome
                        Sobrenome
                    </div>
                </th>
                <th class="text-start" style="width: 12%;">
                    <div class="col-lg-12">
                        e-mail /
                        Data Nasc
                    </div>
                </th>
                <th class="text-start" style="width: 12%;">Equipe</th>
                <th style="width: 18%;">CPF</th>

            </tr>
        </thead>
        <tbody>
            <?php foreach ($atletas as $atleta) { ?>
                <tr>
                    <td><a href="/index_atleta?id=<?= $atleta['IDATLETA'] ?>">
                            <img src="<?= $atleta['fotoAtleta'] ?>" class="img-foto" style="width: 60px; height: 60px; border:0 ">
                        </a>
                    </td>
                    <td><?= $atleta['IDATLETA'] ?></td>
                    <td class="text-start">
                        <?= $atleta['nomeAtleta'] ?>
                        <div class="col-lg-12">
                            <?= $atleta['sobreNomeAtleta'] ?>
                        </div>
                    </td>
                    <td style="font-size: small;" class="text-start"><?= $atleta['emailAtleta'] ?>
                        <div style="font-size: small;" class="col-lg-12">
                            <?php echo implode('/',  array_reverse(explode('-', $atleta['dataNascAtleta']))) ?>
                        </div>
                    </td>
                    <td style="font-size: small;"><?= $atleta['nomeEquipe'] ?></td>
                    <td><?= $atleta['cpfAtleta'] ?></td>
                    <td><a href="/edit_atleta?id=<?= $atleta['IDATLETA'] ?>" class="btn btn-outline-primary">Editar</a></td>
                    <td><button type="button" class="btn btn-danger modalSelectBtn" data-bs-toggle="modal" data-bs-target="#exampleModal" value="<?= $atleta['IDATLETA'] ?>">
                            Delete
                        </button></td>
                </tr>
            <?php } ?>
        </tbody>
    </table>
</div>
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Modal title</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <span><input type="checkbox" id="confirmDelete" class="form-check-input"></span>
                Confirma exclusão do torneio?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <a href="#" id="deleteBtn" class="btn btn-danger disabled">Confirmar</a>
            </div>
        </div>
    </div>
</div>
<script>
    let buttons = document.getElementsByClassName('modalSelectBtn');
    let enableDelete = document.getElementById('confirmDelete');
    let deleteBtn = document.getElementById('deleteBtn');
    let hrefDeleteLink = ""

    for(let btn of buttons){
        btn.addEventListener('click', (e)=>{
            deleteBtn.classList.add('disabled');
            enableDelete.checked = false;
            hrefDeleteLink = "/delete_atleta?id=" + btn.value;
            deleteBtn.href = hrefDeleteLink;
        })
    }
    enableDelete.addEventListener('change', (e)=> {
        if(enableDelete.checked === true) {
            deleteBtn.classList.remove('disabled');
        } else {
            deleteBtn.classList.add('disabled');
        }
    })
</script>
