<?php

$equipes = $this->viewData->equipes;

echo '<pre>';
//print_r($equipes);
echo '</pre>';

?>


<div class="py-5 text-center">
    <h2 class="display-5 my-3">Administração de Equipes</h2>
</div>

<div class="text-end">
    <a href="/add_equipe">
        <i class="bi bi-plus-circle" style="font-size: 32px; color: rgba(var(--bs-secondary-color-rgb), 0.5)"></i>
    </a>
</div>

<div class="table-responsive">
    <table class="table text-center">
        <thead>
            <tr>

                <th style="width: 12%;"></th>
                <th style="width: 12%;">ID</th>
                <th class="text-start" style="width: 32%;">Equipe</th>
                <th class="text-start" style="width: 42%;">Nome</th>

            </tr>
        </thead>
        <tbody>
            <?php foreach ($equipes as $equipe) { ?>
                <tr>
                    <td><img src="<?= $equipe['logoEquipe'] ?>" class="img-foto" style="width: 60px; height: 60px; border:0 " alt="Logotipo da <?= $equipe['nomeEquipe'] ?>"></td>
                    <td><?= $equipe['IDEQUIPE'] ?></td>
                    <td class="text-start"><?= $equipe['nomeFantasiaEquipe'] ?></td>
                    <td class="text-start"><?= $equipe['nomeEquipe'] ?></td>
                    <td><a href="edit_equipe?idequipe=<?= $equipe['IDEQUIPE'] ?>" class="btn btn-outline-primary">Editar</a></td>
                    <td><a href="delete_equipe?idequipe=<?= $equipe['IDEQUIPE'] ?>" class="btn btn-danger">Delete</a></td>
                </tr>
            <?php } ?>
        </tbody>
    </table>
</div>
