<link rel="stylesheet" href="./css/progress_circle.css">

<div class="col-md-6">
    <div class="progress blue">
        <span class="progress-left">
            <span class="progress-bar"></span>
        </span>
        <span class="progress-right">
            <span class="progress-bar"></span>
        </span>
        <div class="progress-value">30</div>
    </div>

    <div class="progress yellow">
        <span class="progress-left">
            <span class="progress-bar"></span>
        </span>
        <span class="progress-right">
            <span class="progress-bar"></span>
        </span>
        <div class="progress-value">37.5%</div>
    </div>
</div>
