<!-- <link rel="stylesheet" href="./css/progress_circle.css"> -->
<?php
$total_atletas = $this->viewData->count_atletas;
$total_equipes = $this->viewData->count_equipes;
$total_complexos = $this->viewData->count_complexos;
$total_torneios = $this->viewData->count_torneios;

?>
<div class="container mt-5">
    <div class="py-5 text-center">
        <h2 class="display-5 my-3">Gerenciamento da aplicação</h2>
        <!-- <p class="lead">Alteração dos dados</p> -->
    </div>
    <div class="d-flex flex-row mb-5 justify-content-around">
        <div class="d-flex flex-column justify-content-center align-items-center">
            <p class="d-flex justify-content-center align-items-center display-4 index-admin-data"><?= $total_atletas ?></p>
            <p class="lead text-center">Atletas Cadastrados</p>
        </div>
        <div class="d-flex flex-column justify-content-center align-items-center">
            <p class="d-flex justify-content-center align-items-center display-4 index-admin-data"><?= $total_equipes ?></p>
            <p class="lead text-center">Equipes Cadastradas</p>
        </div>
    </div>
    <div class="d-flex flex-row justify-content-around">
        <div class="d-flex flex-column justify-content-center align-items-center">
            <p class="d-flex justify-content-center align-items-center display-4 index-admin-data"><?= $total_complexos ?></p>
            <p class="lead text-center">Piscinas Cadastradas</p>
        </div>
        <div class="d-flex flex-column justify-content-center align-items-center">
            <p class="d-flex justify-content-center align-items-center display-4 index-admin-data"><?= $total_torneios ?></p>
            <p class="lead text-center">Torneios Cadastrados</p>
        </div>
    </div>

</div>
