<?php

$indices = $this->viewData->indices;
$anos = $this->viewData->anosIndice;
$tipos = $this->viewData->tipoIndice;
$categorias = $this->viewData->categorias;
$piscinas = $this->viewData->piscinas;
$estilos = $this->viewData->estilos;
$generos = ['F', 'M'];
$array_indice = [];

$countIndices = 1;
$countPiscinas = 1;
$countTipos = 1;

echo "<pre>";
//print_r($array_indice);
//print_r($indices);
// print_r($anos);
//print_r($tipos);
// print_r($piscinas);
// echo '<br>';
// var_dump(array_search('2024', array_column($indices, 'anoIndice')));
//print_r($estilos);
//print_r($estilos['distancia'] . 'm ' . $estilos['nomeEstilo']);
echo '</pre>';
?>
<style>
    a {
        text-decoration: none;
        color: #2c0b0e;
    }
</style>

<div class="py-5 text-center">
    <h2 class="fw-light">Tabela de Índices</h2>
    <p class="lead"></p>
</div>
<div class="row p-3 ">
    <form action="save_indice" method="POST" class="needs-validation" enctype="multipart/form-data">
        <div class="row">
            <div class="row d-flex justify-content-around align-items-end">
                <div class="col-md-2">
                    <label for="anoIndice" class="form-label">Ano Índice</label>
                    <select class="form-select" name="anoIndice" id="anoIndice">
                        <option value="">Selected</option>
                        <?php foreach ($anos as $ano) { ?>
                            <option value="<?= $ano ?>"><?= $ano ?></option>
                        <?php } ?>
                    </select>
                </div>
                <div class="col-md-2">
                    <label for="nomeTorneio" class="form-label">Tipo Índice</label>
                    <input class="form-select" list="tipoIndice" name="tipoIndice">
                    <datalist id="tipoIndice">
                        <?php foreach ($tipos as $tipo) { ?>
                            <option value="<?= $tipo ?>">
                            <?php } ?>
                    </datalist>
                </div>
                <div class="col-md-2">
                    <label for="estiloIndice" class="form-label">Estilo</label>
                    <select class="form-select" name="id_distanciaestilo" id="estiloIndice">
                        <option value="">Selected</option>
                        <?php foreach ($estilos as $estilo) { ?>
                            <option value="<?= $estilo['IDDISTANCIAESTILO'] ?>"><?= $estilo['distancia'] . 'm ' . $estilo['nomeEstilo'] ?></option>
                        <?php } ?>
                    </select>
                </div>
                <div class="col-md-2">
                    <label for="piscinaIndice" class="form-label">Piscina</label>
                    <select class="form-select" name="id_piscina" id="piscinaIndice">
                        <option value="">Selected</option>
                        <?php foreach ($piscinas as $key => $value) { ?>
                            <option value="<?= $key ?>"><?= $value . 'm' ?></option>
                        <?php } ?>
                    </select>
                </div>
            </div>
            <div class="row d-flex justify-content-around align-items-end">
                <div class="col-md-2">
                    <label for="categoriaIndice" class="form-label">Categoria</label>
                    <select class="form-select" name="id_categoria" id="categoriaIndice">
                        <option value="">Selected</option>
                        <?php foreach ($categorias as $categoria) { ?>
                            <option value="<?= $categoria['IDCATEGORIA'] ?>"><?= $categoria['nomeCategoria'] ?></option>
                        <?php } ?>
                    </select>
                </div>
                <div class="col-md-2">
                    <label for="generoIndice" class="form-label">Genero</label>
                    <select class="form-select" name="generoIndice" id="generoIndice">
                        <option value="">Selected</option>
                        <option value="F">Feminino</option>
                        <option value="M">Masculino</option>
                    </select>
                </div>
                <div class="col-md-2">
                    <label for="tempoIndice" class="form-label">Tempo</label>
                    <input type="text" name="tempoIndice" class="form-control" placeholder="00:00.00" id="tempoIndice">
                </div>
                <div class="col-md-2">
                    <button class="btn btn-primary h-25 w-100" type="submit">Incluir</button>
                </div>
            </div>
        </div>
        <hr class="my-4">
    </form>
    <form action="filtra_indices_tabela" method="post" class="row g-3 d-flex align-items-end">
        <div class="d-flex justify-content-around align-items-end">
            <div class="col-md-4 col-lg-2">
                <label for="anoIndice" class="form-label">Ano</label>
                <select name="anoIndice" class="form-select" id="anoIndice">
                    <option value="">Selecione</option>
                    <?php foreach ($anos as $ano) { ?>
                        <option value="<?= $ano ?>"><?= $ano ?></option>
                    <?php }; ?>
                </select>
            </div>
            <div class="col-md-4 col-lg-2">
                <label for="tipoIndice" class="form-label">Tipo</label>
                <select name="tipoIndice" class="form-select" id="tipoIndice">
                    <option value="">Selecione</option>
                    <?php foreach ($tipos as $tipo) { ?>
                        <option value="<?= $tipo ?>"><?= $tipo ?></option>
                    <?php }; ?>
                </select>
            </div>
            <div class="col-md-4 col-lg-2">
                <label for="generoIndice" class="form-label">Genero</label>
                <select name="generoIndice" class="form-select" id="generoIndice">
                    <option value="">Selecione</option>
                    <option value="F">Feminino</option>
                    <option value="M">Masculino</option>
                </select>
            </div>
            <div class="col-md-4 col-lg-2">
                <label for="categoriaIndice" class="form-label">Categoria</label>
                <select name="id_categoria" class="form-select" id="categoriaIndice">
                    <option value="">Selecione</option>
                    <?php foreach ($categorias as $categoria) { ?>
                        <option value="<?= $categoria['IDCATEGORIA'] ?>"><?= $categoria['nomeCategoria'] ?></option>
                    <?php }; ?>
                </select>
            </div>
            <div class="col-md-4 col-lg-2">
                <input type="submit" class="form-control btn btn-primary" value="Filtrar" id="filtrar">
            </div>
        </div>
    </form>
</div>

<div class="table-responsive small">
    <?php foreach ($anos as $ano) { ?>
        <?php if ((array_search($ano, array_column($indices, 'anoIndice'))) !== false) { ?>
            <h2><?= $ano ?></h2>
            <?php foreach ($tipos as $tipo) { ?>
                <?php if ((array_search($tipo, array_column($indices, 'tipoIndice'))) !== false) {
                ?>
                    <h3><?= $tipo ?></h3>
                    <?php foreach ($piscinas as $piscina) { ?>
                        <?php if ((array_search($piscina, array_column($indices, 'tamanhoPiscina'))) !== false) {
                        ?>
                            <h3 class="lead"><?= 'Tamanho da piscina: ' . $piscina . ' m' ?></h3>
                            <?php
                            foreach ($generos as $genero) { ?>
                                <?php if ((array_search($genero, array_column($indices, 'generoIndice'))) !== false) {
                                ?>
                                    <h3 class="lead"><?= 'Genero: ' . $genero ?></h3>
                                <?php } ?>
                                <table class="table table-sm mx-auto collapse" id="indices-<?= $countIndices ?>" >
                                    <thead>
                                        <tr>
                                            <th class="col-sm-1">Estilo</th>
                                            <?php foreach ($categorias as $categoria) {
                                                if ($categoria['IDCATEGORIA'] > 7) { ?>
                                                    <th class="col-sm-1" class="text-center"><?= $categoria['nomeCategoria'] ?></th>
                                            <?php }
                                            } ?>
                                        </tr>
                                    </thead>
                                    <button type="button" class="btn btn-outline-primary" data-bs-toggle="collapse" data-bs-target="#indices-<?= $countIndices ?>" aria-expanded="false" aria-controls="collapseExample">Ver</button>
<!--                                    //TODO Ajustar a tabela para não mostrar valores vazios-->
                                    <tbody >
                                        <?php foreach ($estilos as $estilo) { ?>
                                            <tr class="mb-1">
                                                <?php if ((array_search($estilo['IDDISTANCIAESTILO'], array_column($indices, 'ID_DISTANCIAESTILO'))) !== false) { ?>
                                                    <th scope="row" style="width: 200px;"><?= $estilo['distancia'] . 'm ' . $estilo['nomeEstilo'] ?></th>
                                                    <td><?php
                                                        foreach ($indices as $indice) {
                                                            if ($indice['tipoIndice'] == $tipo && $indice['anoIndice'] == $ano && $indice['tamanhoPiscina'] == $piscina && $indice['generoIndice'] == $genero && $indice['ID_DISTANCIAESTILO'] == $estilo['IDDISTANCIAESTILO'] && $indice['ID_CATEGORIA'] == '8') { ?>
                                                                <a href="/view_indice?id=<?= $indice['IDINDICE'] ?>"><?= adjustTime($indice['tempoIndice']) ?? '00:00.00' ?> </a>
                                                            <?php }
                                                        } ?>
                                                    </td>
                                                    <td><?php
                                                        foreach ($indices as $indice) {
                                                            if ($indice['tipoIndice'] == $tipo && $indice['anoIndice'] == $ano && $indice['tamanhoPiscina'] == $piscina && $indice['generoIndice'] == $genero && $indice['ID_DISTANCIAESTILO'] == $estilo['IDDISTANCIAESTILO'] && $indice['ID_CATEGORIA'] == '9') { ?>
                                                                <a href="/view_indice?id=<?= $indice['IDINDICE'] ?>"><?= adjustTime($indice['tempoIndice']) ?? '00:00.00' ?> </a>
                                                            <?php }
                                                        } ?>
                                                    </td>
                                                    <td><?php
                                                        foreach ($indices as $indice) {
                                                            if ($indice['tipoIndice'] == $tipo && $indice['anoIndice'] == $ano && $indice['tamanhoPiscina'] == $piscina && $indice['generoIndice'] == $genero && $indice['ID_DISTANCIAESTILO'] == $estilo['IDDISTANCIAESTILO'] && $indice['ID_CATEGORIA'] == '10') { ?>
                                                                <a href="/view_indice?id=<?= $indice['IDINDICE'] ?>"><?= adjustTime($indice['tempoIndice']) ?? '00:00.00' ?> </a>
                                                            <?php }
                                                        } ?>
                                                    </td>
                                                    <td><?php
                                                        foreach ($indices as $indice) {
                                                            if ($indice['tipoIndice'] == $tipo && $indice['anoIndice'] == $ano && $indice['tamanhoPiscina'] == $piscina && $indice['generoIndice'] == $genero && $indice['ID_DISTANCIAESTILO'] == $estilo['IDDISTANCIAESTILO'] && $indice['ID_CATEGORIA'] == '11') { ?>
                                                                <a href="/view_indice?id=<?= $indice['IDINDICE'] ?>"><?= adjustTime($indice['tempoIndice']) ?? '00:00.00' ?> </a>
                                                            <?php }
                                                        } ?>
                                                    </td>
                                                    <td><?php
                                                        foreach ($indices as $indice) {
                                                            
                                                            if ($indice['tipoIndice'] == $tipo && $indice['anoIndice'] == $ano && $indice['tamanhoPiscina'] == $piscina && $indice['generoIndice'] == $genero && $indice['ID_DISTANCIAESTILO'] == $estilo['IDDISTANCIAESTILO'] && $indice['ID_CATEGORIA'] == '12') { ?>
                                                                <a href="/view_indice?id=<?= $indice['IDINDICE'] ?>"><?= adjustTime($indice['tempoIndice']) ?? '00:00.00' ?> </a>
                                                            <?php }
                                                        } ?>
                                                    </td>
                                                    <td><?php
                                                        foreach ($indices as $indice) {
                                                            if ($indice['tipoIndice'] == $tipo && $indice['anoIndice'] == $ano && $indice['tamanhoPiscina'] == $piscina && $indice['generoIndice'] == $genero && $indice['ID_DISTANCIAESTILO'] == $estilo['IDDISTANCIAESTILO'] && $indice['ID_CATEGORIA'] == '13') { ?>
                                                                <a href="/view_indice?id=<?= $indice['IDINDICE'] ?>"><?= adjustTime($indice['tempoIndice']) ?? '00:00.00' ?> </a>
                                                           <?php }
                                                        } ?>
                                                    </td>
                                                    <td><?php
                                                        foreach ($indices as $indice) {
                                                            if ($indice['tipoIndice'] == $tipo && $indice['anoIndice'] == $ano && $indice['tamanhoPiscina'] == $piscina && $indice['generoIndice'] == $genero && $indice['ID_DISTANCIAESTILO'] == $estilo['IDDISTANCIAESTILO'] && $indice['ID_CATEGORIA'] == '14') { ?>
                                                                <a href="/view_indice?id=<?= $indice['IDINDICE'] ?>"><?= adjustTime($indice['tempoIndice']) ?? '00:00.00' ?> </a>
                                                            <?php }
                                                        } ?>
                                                    </td>
                                                    <td><?php
                                                        foreach ($indices as $indice) {
                                                            if ($indice['tipoIndice'] == $tipo && $indice['anoIndice'] == $ano && $indice['tamanhoPiscina'] == $piscina && $indice['generoIndice'] == $genero && $indice['ID_DISTANCIAESTILO'] == $estilo['IDDISTANCIAESTILO'] && $indice['ID_CATEGORIA'] == '15') { ?>
                                                                <a href="/view_indice?id=<?= $indice['IDINDICE'] ?>"><?= adjustTime($indice['tempoIndice']) ?? '00:00.00' ?> </a>
                                                            <?php }
                                                        } ?>
                                                    </td>
                                                    <td><?php
                                                        foreach ($indices as $indice) {
                                                            if ($indice['tipoIndice'] == $tipo && $indice['anoIndice'] == $ano && $indice['tamanhoPiscina'] == $piscina && $indice['generoIndice'] == $genero && $indice['ID_DISTANCIAESTILO'] == $estilo['IDDISTANCIAESTILO'] && $indice['ID_CATEGORIA'] == '16') { ?>
                                                                <a href="/view_indice?id=<?= $indice['IDINDICE'] ?>"><?= adjustTime($indice['tempoIndice']) ?? '00:00.00' ?> </a>
                                                            <?php }
                                                        } ?>
                                                    </td>
                                                    <td><?php
                                                        foreach ($indices as $indice) {
                                                            if ($indice['tipoIndice'] == $tipo && $indice['anoIndice'] == $ano && $indice['tamanhoPiscina'] == $piscina && $indice['generoIndice'] == $genero && $indice['ID_DISTANCIAESTILO'] == $estilo['IDDISTANCIAESTILO'] && $indice['ID_CATEGORIA'] == '17') { ?>
                                                                <a href="/view_indice?id=<?= $indice['IDINDICE'] ?>"><?= adjustTime($indice['tempoIndice']) ?? '00:00.00' ?> </a>
                                                            <?php }
                                                        } ?>
                                                    </td>
                                                    <td><?php
                                                        foreach ($indices as $indice) {
                                                            if ($indice['tipoIndice'] == $tipo && $indice['anoIndice'] == $ano && $indice['tamanhoPiscina'] == $piscina && $indice['generoIndice'] == $genero && $indice['ID_DISTANCIAESTILO'] == $estilo['IDDISTANCIAESTILO'] && $indice['ID_CATEGORIA'] == '18') { ?>
                                                                <a href="/view_indice?id=<?= $indice['IDINDICE'] ?>"><?= adjustTime($indice['tempoIndice']) ?? '00:00.00' ?> </a>
                                                            <?php }
                                                        } ?>
                                                    </td>
                                                    <td><?php
                                                        foreach ($indices as $indice) {
                                                            if ($indice['tipoIndice'] == $tipo && $indice['anoIndice'] == $ano && $indice['tamanhoPiscina'] == $piscina && $indice['generoIndice'] == $genero && $indice['ID_DISTANCIAESTILO'] == $estilo['IDDISTANCIAESTILO'] && $indice['ID_CATEGORIA'] == '99') { ?>
                                                                <a href="/view_indice?id=<?= $indice['IDINDICE'] ?>"><?= adjustTime($indice['tempoIndice']) ?? '00:00.00' ?> </a>
                                                            <?php }
                                                        } ?>
                                                    </td>
                                                <?php } ?>
                                            </tr>
                                        <?php } ?>
                                    </tbody>
                                </table>
                                <hr>
                                <?php $countIndices++; ?>
                            <?php                              
                            } ?>
                        <?php
                        }
                    }
                }
            }
        } ?>
       
    <?php } ?>
</div>

<script>
    VMasker(document.querySelector('#tempoIndice')).maskPattern('99:99.99');
</script>
