<?php

$torneios = $this->viewData->torneios;

?>

<div class="py-5 text-center">
    <h2 class="display-5 my-3">Administração de Torneios</h2>
</div>

<div class="text-end">
    <a href="/add_torneio">
        <i class="bi bi-plus-circle" style="font-size: 32px; color: rgba(var(--bs-secondary-color-rgb), 0.5)"></i>
    </a>
</div>

<div class="table-responsive">
    <table class="table text-center">
        <thead>
            <tr>
                <th style="width: 8%;">ID</th>
                <th class="text-start" style="width: 32%;">Torneio</th>
                <th class="text-start" style="width: 12%;">Data</th>
                <th style="width: 32%;">Piscina</th>
                <th style="width: 8%;"></th>
                <th style="width: 12%;"></th>
                <th style="width: 12%;"></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($torneios as $torneio) { ?>
                <tr>
                    <td><?= $torneio['IDTORNEIO'] ?></td>
                    <td class="text-start"><?= $torneio['nomeTorneio'] ?></td>
                    <td class="text-start"><?php echo implode('/',  array_reverse(explode('-', $torneio['dataTorneio']))) ?></td>
                    <td><?= $torneio['nomeFantasiaComplexo'] ?></td>
                    <td><?= $torneio['tamanhoPiscina'] . 'm' ?></td>
                    <td><a href="/edit_torneio?id=<?= $torneio['IDTORNEIO'] ?>" class="btn btn-outline-primary">Editar</a></td>
                    <td><button type="button" class="btn btn-danger modalSelectBtn" data-bs-toggle="modal" data-bs-target="#exampleModal" value="<?= $torneio['IDTORNEIO'] ?>">
                            Delete
                        </button></td>
                </tr>
            <?php } ?>
        </tbody>
    </table>
</div>
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Modal title</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <span><input type="checkbox" id="confirmDelete" class="form-check-input"></span>
                Confirma exclusão do torneio?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <a href="#" id="deleteBtn" class="btn btn-danger disabled">Confirmar</a>
            </div>
        </div>
    </div>
</div>
<script>
    let buttons = document.getElementsByClassName('modalSelectBtn');
    let enableDelete = document.getElementById('confirmDelete');
    let deleteBtn = document.getElementById('deleteBtn');
    let hrefDeleteLink = ""

    for (let btn of buttons) {
        btn.addEventListener('click', (e) => {
            deleteBtn.classList.add('disabled');
            enableDelete.checked = false;
            hrefDeleteLink = "/delete_torneio?id=" + btn.value;
            deleteBtn.href = hrefDeleteLink;
        })
    }
    enableDelete.addEventListener('change', (e) => {
        if (enableDelete.checked === true) {
            deleteBtn.classList.remove('disabled');
        } else {
            deleteBtn.classList.add('disabled');
        }
    })
</script>
