<?php

$torneios = $this->viewData->torneios;

?>

<div class="py-5 text-center">
    <h2 class="display-5 my-3">Administração de Torneios</h2>
</div>

<div class="text-end">
    <a href="/add_torneio">
        <i class="bi bi-plus-circle" style="font-size: 32px; color: rgba(var(--bs-secondary-color-rgb), 0.5)"></i>
    </a>
</div>

<div class="table-responsive">
    <table class="table text-center">
        <thead>
            <tr>
                <th style="width: 8%;">ID</th>
                <th class="text-start" style="width: 32%;">Torneio</th>
                <th class="text-start" style="width: 12%;">Data</th>
                <th style="width: 32%;">Piscina</th>
                <th style="width: 8%;"></th>
                <th style="width: 12%;"></th>
                <th style="width: 12%;"></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($torneios as $torneio) { ?>
                <tr>
                    <td><?= $torneio['IDTORNEIO'] ?></td>
                    <td class="text-start"><?= $torneio['nomeTorneio'] ?></td>
                    <td class="text-start"><?php echo implode('/',  array_reverse(explode('-', $torneio['dataTorneio']))) ?></td>
                    <td><?= $torneio['nomeFantasiaComplexo'] ?></td>
                    <td><?= $torneio['tamanhoPiscina'] . 'm' ?></td>
                    <!-- //TODO: Implementar a função de editar -->
                    <td><a href="" class="btn btn-outline-primary">Editar</a></td>
                    <td><a href="delete_torneio?id=<?= $torneio['IDTORNEIO'] ?>" class="btn btn-danger">Delete</a></td>
                </tr>
            <?php } ?>
        </tbody>
    </table>
</div>
