<?php

$users = $this->viewData->users;

?>

<div class="py-5 text-center">
    <h2 class="display-5 my-3">Administração de Usuários</h2>
    <!-- <p class="lead">Alteração dos dados</p> -->
</div>

<!-- //TODO: implementar a função de adicionar -->
<div class="text-end">
    <a href="/">
        <i class="bi bi-plus-circle" style="font-size: 32px; color: rgba(var(--bs-secondary-color-rgb), 0.5)"></i>
    </a>
</div>

<div class="table-responsive">
    <table class="table text-center">
        <thead>
            <tr>
                <th style="width: 12%;">ID</th>
                <th class="text-start" style="width: 32%;">Username</th>
                <th class="text-start" style="width: 22%;">user_name</th>
                <th style="width: 12%;">user_id</th>
                <th style="width: 12%;">Permissão</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($users as $user) { ?>
                <tr>
                    <td><?= $user['IDUSER'] ?></td>
                    <td class="text-start"><?= $user['username'] ?></td>
                    <td class="text-start"><?= $user['user_name'] ?></td>
                    <td><?= $user['user_id'] ?></td>
                    <td><?= $user['permission'] ?></td>
                    <!-- //TODO: implementar a função de editar e deletar -->
                    <td><a href="/edit_user?id=<?= $user['IDUSER'] ?>" class="btn btn-outline-primary">Editar</a></td>
                    <td><a href="/delete_user?id=<?= $user['IDUSER'] ?>" class="btn btn-danger">Delete</a></td>
                </tr>
            <?php } ?>
        </tbody>
    </table>
</div>
