<?php

$users = $this->viewData->users;

?>

<div class="py-5 text-center">
    <h2 class="display-5 my-3">Administração de Usuários</h2>
    <!-- <p class="lead">Alteração dos dados</p> -->
</div>

<!-- //TODO: implementar a função de adicionar -->
<div class="text-end">
    <a href="/add_user">
        <i class="bi bi-plus-circle" style="font-size: 32px; color: rgba(var(--bs-secondary-color-rgb), 0.5)"></i>
    </a>
</div>

<div class="table-responsive">
    <table class="table text-center">
        <thead>
            <tr>
                <th style="width: 12%;">ID</th>
                <th class="text-start" style="width: 32%;">Username (login)</th>
                <th class="text-start" style="width: 22%;">Nome usuário</th>
                <th style="width: 12%;">ID de Atleta</th>
                <th style="width: 12%;">Permissão</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($users as $user) { ?>
                <tr>
                    <td><?= $user['IDUSER'] ?></td>
                    <td class="text-start"><?= $user['username'] ?></td>
                    <td class="text-start"><?= $user['user_name'] ?></td>
                    <td><?= $user['user_id'] ?></td>
                    <td><?= $user['permission'] ?></td>
                    <!-- //TODO: implementar a função de editar e deletar -->
                    <td><a href="/edit_user?id=<?= $user['IDUSER'] ?>" class="btn btn-outline-primary">Editar</a></td>
                    <td><button type="button" class="btn btn-danger modalSelectBtn" data-bs-toggle="modal" data-bs-target="#exampleModal" value="<?= $user['IDUSER'] ?>">
                            Delete
                        </button></td>
                </tr>
            <?php } ?>
        </tbody>
    </table>
</div>
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Modal title</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <span><input type="checkbox" id="confirmDelete" class="form-check-input"></span>
                Confirma exclusão do usuário?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <a href="#" id="deleteBtn" class="btn btn-danger disabled">Confirmar</a>
            </div>
        </div>
    </div>
</div>
<script>
    let buttons = document.getElementsByClassName('modalSelectBtn');
    let enableDelete = document.getElementById('confirmDelete');
    let deleteBtn = document.getElementById('deleteBtn');
    let hrefDeleteLink = ""

    deleteBtn.classList.add('disabled');
    
    for(let btn of buttons){
        btn.addEventListener('click', (e)=>{
            deleteBtn.classList.add('disabled');
            enableDelete.checked = false;
            hrefDeleteLink = "/delete_user?id=" + btn.value;
            deleteBtn.href = hrefDeleteLink;
        })
    }
    enableDelete.addEventListener('change', (e)=> {
        if(enableDelete.checked === true) {
            deleteBtn.classList.remove('disabled');
        } else {
            deleteBtn.classList.add('disabled');
        }
    })
</script>
