<?php
//$location = $this->setHtmlData->referer;
$atleta = $this->viewData->atleta;
// print_r($atleta);

?>
<main class="form-signin w-100 m-auto">
    <form method="post" action="/save_user">

        <input type="hidden" name="idAtleta" value="<?= $atleta['IDATLETA'] ?>">
        <input type="hidden" name="emailAtleta" value="<?= $atleta['emailAtleta'] ?>">
        <img class="mb-4" src="./images/swim_icon.png" alt="" width="72" height="57">
        <h1 class="h3 mb-3 fw-normal">Cadastro de Senha</h1>
        <?php if (isset($_GET['login']) && $_GET['login'] == 'erro') { ?>
            <div class="alert alert-danger">
                <p>Senha invalida</p>
            </div>
        <?php } ?>
        <div class="form-floating">
            <input type="password" class="form-control" id="floatingPassword1" name="passwd" placeholder="senha">
            <label for="floatingPassword1">Digite uma senha</label>
        </div>
        <div class="form-floating">
            <input type="password" class="form-control" id="floatingPassword2" name="passwd_confirm" placeholder="senha">
            <label for="floatingPassword2">Confirme a sua senha</label>
        </div>

        <!-- <div class="form-check text-start my-3">
      <input class="form-check-input" type="checkbox" value="remember-me" id="flexCheckDefault">
      <label class="form-check-label" for="flexCheckDefault">
        Remember me
      </label>
    </div> -->
        <button class="btn btn-primary w-100 py-2" type="submit">Salvar</button>
    </form>
    <!-- <a class="btn btn-primary w-100 py-2 mt-3" href="register">Não tenho cadastro</a> -->
    <p class="mt-5 mb-3 text-body-secondary">&copy; 2017–2024</p>
</main>
