<?php

$atleta = $this->viewData->atleta;
$categoria = $this->viewData->categoria;
$tempoAtleta = $this->viewData->tempoAtleta;
$melhoresTempos = $this->viewData->melhores_tempos;
            
if ($melhoresTempos != null) {
    $melhoresTempos25 = [];
    $melhoresTempos50 = [];
    foreach ($melhoresTempos as $tempo25) {
        if ($tempo25['piscina'] === 25) {
            $melhoresTempos25[] = $tempo25;
        }
    }
    foreach ($melhoresTempos as $tempo50) {
        if ($tempo50['piscina'] === 50) {
            $melhoresTempos50[] = $tempo50;
        }
    }
    $melhoresTempos25 = array_chunk($melhoresTempos25, 3, true);
    $melhoresTempos50 = array_chunk($melhoresTempos50, 3, true);
} else {
    $melhoresTempos25 = [];
    $melhoresTempos50 = [];
}


?>

<div class="pricing-header p-3 pb-md-4 mx-auto text-center">
    <img src="<?= $atleta['fotoAtleta'] ?>" class="img-foto" alt="">
    <h1 class="display-4 fw-normal text-body-emphasis"><?= $atleta['apelidoAtleta'] . ' ' . $atleta['sobreNomeAtleta'] ?></h1>
    <div class="d-flex justify-content-center align-items-center mb-4">
        <img src="<?= $atleta['logoEquipe'] ?>" style="max-height: 100px; object-fit: contain" class="me-4" alt="">
        <p class="fs-5 text-body-secondary"><?= $atleta['nomeFantasiaEquipe'] ?></p>
    </div>
    <p class="fs-5 text-body-secondary"><?php echo implode('/',  array_reverse(explode('-', $atleta['dataNascAtleta']))) ?> - <?= $categoria['nomeCategoria'] ?></p>
    <div class="row">
        <div class="col-md-3">
            <a href="/view_atleta?id=<?= $atleta['IDATLETA'] ?>" class="btn btn-lg btn-primary w-100 m-1">Dados</a>
        </div>
        <div class="col-md-3">
            <a href="/tempos_atleta?id=<?= $atleta['IDATLETA'] ?>" class="btn btn-lg btn-primary w-100 m-1">Tempos</a>
        </div>
        <div class="col-md-3">
            <a href="/view_atleta?id=<?= $atleta['IDATLETA'] ?>" class="btn btn-lg btn-primary w-100 m-1">Treinos</a>
        </div>
        <div class="col-md-3">
            <a href="/view_atleta?id=<?= $atleta['IDATLETA'] ?>" class="btn btn-lg btn-primary w-100 m-1">Biomecanica</a>
        </div>
    </div>
</div>
</header>

<main>
    <?php if(count($melhoresTempos50) > 0) { ?>
    <div id="carousel50" class="carousel carousel-dark slide">
        <div class="carousel-inner">
            <?php for ($i = 0; $i < count($melhoresTempos50); $i++) {
                $tempos50 = ($melhoresTempos50[$i]) ?>
                <div class="carousel-item <?php if ($i == 0) {
                                                echo 'active';
                                            } ?>">
                    <div class=" row row-cols-1 row-cols-md-3 mb-3 text-center ms-5 me-5">
                        <?php foreach ($tempos50 as $tempo) { ?>
                            <div class="col">
                                <div class="card mb-4 rounded-3 shadow-sm" style="height: auto; min-width: 180px">
                                    <div class="card-header py-3 bg-dark-subtle">
                                        <h4 class="my-0 fw-normal"><?= $tempo['distancia'] . 'm ' . $tempo['estilo'] ?> </h4>
                                    </div>
                                    <div class="card-body">
                                        <p>MELHOR TEMPO</p>
                                        <h1 class="card-title pricing-card-title"><?php echo adjustTime($tempo['tempo']) ?></h1>
                                        <ul class="list-unstyled mt-3 mb-4">
                                            <li><?php echo implode('/',  array_reverse(explode('-', $tempo['data']))) ?></li>
                                            <hr class="ms-5 me-5">
                                            <li><?= $tempo['torneio'] ?></li>
                                            <hr class="ms-5 me-5">
                                            <li><?= 'Piscina: ' . $tempo['piscina'] . 'm' ?></li>
                                            <hr class="ms-5 me-5">
                                            <li><?= 'Local: ' . $tempo['complexo'] ?></li>
                                            <hr class="ms-5 me-5">
                                            <li ><?= $tempo['cidade'] ?></li>
                                        </ul>
                                        <form action="graficos_tempo_filtrado" method="post">
                                            <input type="hidden" name="tamanhoPiscina" value="<?= $tempo['piscina'] ?>">
                                            <input type="hidden" name="distanciaEstilo" value="<?= $tempo['distanciaestilo'] ?>">
                                            <input type="hidden" name="nomeTorneio" value="">
                                            <input type="hidden" name="anoTempo" value="">
                                            <button type="submit" class="w-100 btn btn-lg btn-outline-primary">Veja o gráfico</button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        <?php } ?>
                    </div>
                </div>
            <?php } ?>
        </div>
        <button class="carousel-control-prev" type="button" style="justify-content: start; " data-bs-target="#carousel50" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" style="justify-content: end;" data-bs-target="#carousel50" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>
    <?php } ?>

    <?php if(count($melhoresTempos25) > 0) { ?>
    <div id="carousel25" class="carousel carousel-dark slide">
        <div class="carousel-inner">
            <?php for ($i = 0; $i < count($melhoresTempos25); $i++) {
                $tempos25 = ($melhoresTempos25[$i]) ?>
                <div class="carousel-item <?php if ($i == 0) {
                                                echo 'active';
                                            } ?>">
                    <div class=" row row-cols-1 row-cols-md-3 mb-3 text-center ms-5 me-5">
                        <?php foreach ($tempos25 as $tempo25) { ?>
                            <div class="col">
                                <div class="card mb-4 rounded-3 shadow-sm" style="height: auto;">
                                    <div class="card-header py-3 bg-dark-subtle">
                                        <h4 class="my-0 fw-normal"><?= $tempo25['distancia'] . 'm ' . $tempo25['estilo'] ?> </h4>
                                    </div>
                                    <div class="card-body">
                                        <p>MELHOR TEMPO</p>
                                        <h1 class="card-title pricing-card-title"><?php echo adjustTime($tempo25['tempo']) ?></h1>
                                        <ul class="list-unstyled mt-3 mb-4">
                                            <li><?php echo implode('/',  array_reverse(explode('-', $tempo25['data']))) ?></li>
                                            <hr class="ms-5 me-5">
                                            <li><?= $tempo25['torneio'] ?></li>
                                            <hr class="ms-5 me-5">
                                            <li><?= 'Piscina: ' . $tempo25['piscina'] . 'm' ?></li>
                                            <hr class="ms-5 me-5">
                                            <li><?= 'Local: ' . $tempo25['complexo'] ?></li>
                                            <li><?= $tempo25['cidade'] ?></li>
                                        </ul>
                                        <form action="graficos_tempo_filtrado" method="post">
                                            <input type="hidden" name="tamanhoPiscina" value="<?= $tempo25['piscina'] ?>">
                                            <input type="hidden" name="distanciaEstilo" value="<?= $tempo25['distanciaestilo'] ?>">
                                            <input type="hidden" name="nomeTorneio" value="">
                                            <input type="hidden" name="anoTempo" value="">
                                            <button type="submit" class="w-100 btn btn-lg btn-outline-primary">Veja o gráfico</button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        <?php } ?>
                    </div>
                </div>
            <?php } ?>
        </div>
        <button class="carousel-control-prev" type="button" style="justify-content: start;" data-bs-target="#carousel25" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" style="justify-content: end;" data-bs-target="#carousel25" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>
    <?php } ?>

    <h2 class="display-6 text-center mb-4">Últimas Provas</h2>

    <div class="table-responsive">
        <table class="table text-center">
            <thead>
                <tr>
                    <th style="width: 12%;"></th>
                    <th style="width: 22%;">Torneio</th>
                    <th style="width: 22%;">Piscina</th>
                    <th style="width: 22%;">Estilo</th>
                    <th style="width: 22%;">Tempo</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($tempoAtleta as $tempo) { ?>
                    <tr>
                        <th scope="row" class="text-start"><?php echo implode('/',  array_reverse(explode('-', $tempo['dataTorneio']))) ?></th>
                        <td><?= $tempo['nomeTorneio'] ?></td>
                        <td><?= $tempo['tamanhoPiscina'] . 'm' ?></td>
                        <td><?= $tempo['distancia'] . 'm ' . $tempo['nomeEstilo'] ?></td>
                        <td><?php echo adjustTime($tempo['tempoAtleta']) ?></td>
                    </tr>
                <?php } ?>
            </tbody>
        </table>
    </div>
</main>
