<?php

$atleta = $this->viewData->atleta;
$categoria = $this->viewData->categoria;
$tempoAtleta = $this->viewData->tempoAtleta;

function adjustTime($fullTime)
{
    $time = explode(':', $fullTime);
    (array_shift($time));
    return implode(':', $time);
}

// print_r($tempoAtleta);
?>

<div class="pricing-header p-3 pb-md-4 mx-auto text-center">
    <img src="<?= $atleta['fotoAtleta'] ?>" class="img-foto" alt="">
    <h1 class="display-4 fw-normal text-body-emphasis"><?= $atleta['nomeAtleta'] ?></h1>
    <div class="d-flex justify-content-center align-items-center mb-4">
        <img src="<?= $atleta['logoEquipe'] ?>" style="max-height: 100px; object-fit: contain" class="me-4" alt="">
        <p class="fs-5 text-body-secondary"><?= $atleta['nomeFantasiaEquipe'] ?></p>
    </div>
    <p class="fs-5 text-body-secondary"><?php echo implode('/',  array_reverse(explode('-', $atleta['dataNascAtleta']))) ?> - <?= $categoria['nomeCategoria'] ?></p>
    <a href="view_atleta?id=<?= $atleta['IDATLETA'] ?>" class="btn btn-lg btn-primary">Ver atleta</a>
</div>
</header>

<main>

    <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
        <?php foreach ($tempoAtleta as $tempo) { ?>
            <div class="col">
                <div class="card mb-4 rounded-3 shadow-sm" style="height: 400px;">
                    <div class="card-header py-3">
                        <h4 class="my-0 fw-normal"><?= $tempo['distancia'] . 'm ' . $tempo['nomeEstilo'] ?> </h4>
                    </div>
                    <div class="card-body">
                        <p>MELHOR TEMPO</p>
                        <h1 class="card-title pricing-card-title"><?php echo adjustTime($tempo['tempoAtleta']) ?></h1>
                        <ul class="list-unstyled mt-3 mb-4">
                            <li><?php echo implode('/',  array_reverse(explode('-', $tempo['dataTorneio']))) ?></li>
                            <li><?= $tempo['nomeTorneio'] ?></li>
                            <li><?= 'Piscina: ' . $tempo['tamanhoPiscina'] . 'm' ?></li>
                            <li>Local???</li>
                        </ul>
                        <button type="button" class="w-100 btn btn-lg btn-outline-primary">Sign up for free</button>
                    </div>
                </div>
            </div>
        <?php } ?>
    </div>

    <h2 class="display-6 text-center mb-4">Últimas Provas</h2>

    <div class="table-responsive">
        <table class="table text-center">
            <thead>
                <tr>
                    <th style="width: 12%;"></th>
                    <th style="width: 22%;">Torneio</th>
                    <th style="width: 22%;">Piscina</th>
                    <th style="width: 22%;">Estilo</th>
                    <th style="width: 22%;">Tempo</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($tempoAtleta as $tempo) { ?>
                    <tr>
                        <th scope="row" class="text-start"><?php echo implode('/',  array_reverse(explode('-', $tempo['dataTorneio']))) ?></th>
                        <td><?= $tempo['nomeTorneio'] ?></td>
                        <td><?= $tempo['tamanhoPiscina'] . 'm' ?></td>
                        <td><?= $tempo['distancia'] . 'm ' . $tempo['nomeEstilo'] ?></td>
                        <td><?php echo adjustTime($tempo['tempoAtleta']) ?></td>
                    </tr>
                <?php } ?>
            </tbody>
        </table>
    </div>
</main>
