<?php

$atleta = $this->viewData->atleta;
$categoria = $this->viewData->categoria;
$equipes = $this->viewData->equipes;
?>

<!-- <div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
  <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center" id="bd-theme" type="button" aria-expanded="false" data-bs-toggle="dropdown" aria-label="Toggle theme (auto)">
    <svg class="bi my-1 theme-icon-active" width="1em" height="1em">
      <use href="#circle-half"></use>
    </svg>
    <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
  </button>
  <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
    <li>
      <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light" aria-pressed="false">
        <svg class="bi me-2 opacity-50" width="1em" height="1em">
          <use href="#sun-fill"></use>
        </svg>
        Light
        <svg class="bi ms-auto d-none" width="1em" height="1em">
          <use href="#check2"></use>
        </svg>
      </button>
    </li>
    <li>
      <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark" aria-pressed="false">
        <svg class="bi me-2 opacity-50" width="1em" height="1em">
          <use href="#moon-stars-fill"></use>
        </svg>
        Dark
        <svg class="bi ms-auto d-none" width="1em" height="1em">
          <use href="#check2"></use>
        </svg>
      </button>
    </li>
    <li>
      <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto" aria-pressed="true">
        <svg class="bi me-2 opacity-50" width="1em" height="1em">
          <use href="#circle-half"></use>
        </svg>
        Auto
        <svg class="bi ms-auto d-none" width="1em" height="1em">
          <use href="#check2"></use>
        </svg>
      </button>
    </li>
  </ul>
</div> -->


<div class="container">
  <main>
    <div class="py-5 text-center">
      <img src="<?= $atleta['fotoAtleta'] ?>" class="img-foto" alt="">
      <h2>Dados do Atleta</h2>
      <p class="lead">Alteração dos dados</p>
    </div>

    <div class="row g-5">
      <div class="col-md-5 col-lg-4 order-md-last">
        <h4 class="d-flex justify-content-between align-items-center mb-3">
          <span class="text-primary">Últimas provas</span>
          <span class="badge bg-primary rounded-pill">?</span>
        </h4>
        <ul class="list-group mb-3">
          <li class="list-group-item d-flex justify-content-between lh-sm">
            <div>
              <h6 class="my-0"><a href="#" class="text-decoration-none">Prova</a></h6>
              <small class="text-body-secondary">Torneio</small>
              <h6 class="text-body-secondary">11/11/2024</h6>
            </div>
            <span class="text-body-secondary">00:00.00</span>
          </li>
          <li class="list-group-item d-flex justify-content-between lh-sm">
            <div>
              <h6 class="my-0"><a href="#" class="text-decoration-none">Prova</a></h6>
              <small class="text-body-secondary">Torneio</small>
              <h6 class="text-body-secondary">11/11/2024</h6>
            </div>
            <span class="text-body-secondary">00:00.00</span>
          </li>
          <li class="list-group-item d-flex justify-content-between lh-sm">
            <div>
              <h6 class="my-0"><a href="#" class="text-decoration-none">Prova</a></h6>
              <small class="text-body-secondary">Torneio</small>
              <h6 class="text-body-secondary">11/11/2024</h6>
            </div>
            <span class="text-body-secondary">00:00.00</span>
          </li>
          <li class="list-group-item d-flex justify-content-between bg-body-tertiary">
            <div>
              <h6 class="my-0"><a href="#" class="text-decoration-none">Prova</a></h6>
              <small class="text-body-secondary">Torneio</small>
              <h6 class="text-body-secondary">11/11/2024</h6>
            </div>
            <span class="text-body-secondary">00:00.00</span>
          </li>

        </ul>

        <!-- <form class="card p-2">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Promo code">
            <button type="submit" class="btn btn-secondary">Redeem</button>
          </div>
        </form> -->
      </div>
      <div class="col-md-7 col-lg-8">
        <h4 class="mb-3"></h4>
        <form class="needs-validation" novalidate>
          <div class="row g-3">
            <div class="col-sm-6">
              <label for="firstName" class="form-label">Nome</label>
              <input type="text" class="form-control" id="firstName" placeholder="Nome" value="<?= $atleta['nomeAtleta'] ?>" required>
              <div class="invalid-feedback">
                Valid first name is required.
              </div>
            </div>

            <div class="col-sm-6">
              <label for="lastName" class="form-label">Sobrenome</label>
              <input type="text" class="form-control" id="lastName" placeholder="Sobrenome" value="<?= $atleta['sobreNomeAtleta'] ?>">
              <div class="invalid-feedback">
                Valid last name is required.
              </div>
            </div>

            <div class="col-sm-6">
              <label for="nickname" class="form-label">Apelido</label>

              <input type="text" class="form-control" id="nickname" placeholder="Apelido" value="<?= $atleta['apelidoAtleta'] ?>">
              <!-- <div class="invalid-feedback">
                  Your username is required.
                </div> -->

            </div>

            <div class="col-md-6">

              <div class="row">
                <label for="birth_date" class="form-label">Data de Nascimento</label>
                <div class="col-md-6">
                  <input type="text" class="form-control" id="birth_date" placeholder="" value="<?php echo implode('/', array_reverse(explode('-', $atleta['dataNascAtleta']))); ?>">

                </div>
                <div class="col-md-6">
                  <p><?= $categoria['nomeCategoria'] ?></p>
                </div>
                <!-- <div class=" invalid-feedback">
                  Your username is required.
                </div> -->
              </div>
            </div>

            <div class="col-12">
              <label for="email" class="form-label">Email</label>
              <input type="email" class="form-control" id="email" placeholder="you@example.com" value="<?= $atleta['emailAtleta'] ?>">
              <div class="invalid-feedback">
                Please enter a valid email address.
              </div>
            </div>

            <div class="col-12">
              <label for="address" class="form-label">Address</label>
              <input type="text" class="form-control" id="address" placeholder="1234 Main St" required>
              <div class="invalid-feedback">
                Please enter your shipping address.
              </div>
            </div>

            <div class="col-12">
              <label for="address2" class="form-label">Address 2 <span class="text-body-secondary">(Optional)</span></label>
              <input type="text" class="form-control" id="address2" placeholder="Apartment or suite">
            </div>

            <div class="col-md-5">
              <label for="country" class="form-label">Country</label>
              <select class="form-select" id="country" required>
                <option value="">Choose...</option>
                <option>United States</option>
              </select>
              <div class="invalid-feedback">
                Please select a valid country.
              </div>
            </div>

            <div class="col-md-4">
              <label for="state" class="form-label">State</label>
              <select class="form-select" id="state" required>
                <option value="">Choose...</option>
                <option>California</option>
              </select>
              <div class="invalid-feedback">
                Please provide a valid state.
              </div>
            </div>

            <div class="col-md-3">
              <label for="zip" class="form-label">Zip</label>
              <input type="text" class="form-control" id="zip" placeholder="" required>
              <div class="invalid-feedback">
                Zip code required.
              </div>
            </div>
          </div>

          <!-- <hr class="my-4">

          <div class="form-check">
            <input type="checkbox" class="form-check-input" id="same-address">
            <label class="form-check-label" for="same-address">Shipping address is the same as my billing address</label>
          </div>

          <div class="form-check">
            <input type="checkbox" class="form-check-input" id="save-info">
            <label class="form-check-label" for="save-info">Save this information for next time</label>
          </div>

          <hr class="my-4"> -->

          <label class="mt-3">Sexo</label>

          <div class="my-3">
            <div class="form-check">
              <input id="masculino" name="sexoAleta" type="radio" class="form-check-input" checked required>
              <label class="form-check-label" for="masculino">Masculino</label>
            </div>
            <div class="form-check">
              <input id="feminino" name="sexoAleta" type="radio" class="form-check-input" required>
              <label class="form-check-label" for="feminino">Feminino</label>
            </div>
            <!-- <div class="form-check">
              <input id="paypal" name="sexoAleta" type="radio" class="form-check-input" required>
              <label class="form-check-label" for="paypal">PayPal</label>
            </div> -->
          </div>

          <div class="row gy-3">
            <div class="col-md-6">
              <label for="cpfAtleta" class="form-label">CPF</label>
              <input type="text" class="form-control" id="cpfAtleta" placeholder="" value="<?= $atleta['cpfAtleta'] ?>">
              <!-- <small class="text-body-secondary">Full name as displayed on card</small>
              <div class="invalid-feedback">
                Name on card is required
              </div> -->
            </div>
            <div class="col-md-6">
              <label for="rgAtleta" class="form-label">RG</label>
              <input type="text" class="form-control" id="rgAtleta" placeholder="" value="<?= $atleta['rgAtleta'] ?>">
              <!-- <div class="invalid-feedback">
                Expiration date required
              </div> -->
            </div>

            <div class="col-md-4">
              <label for="cc-number" class="form-label">Registro na Federação</label>
              <input type="text" class="form-control" id="cc-number" placeholder="" value="<?= $atleta['numRegistroAtleta'] ?>">
              <!-- <div class="invalid-feedback">
                Credit card number is required
              </div> -->
            </div>


            <div class="col-md-8">
              <label for="equipeAtleta" class="form-label">CVV</label>
              <select class="form-select" name="equipeAtleta" id="equipeAtleta">
                <option value="">Selected</option>
                <?php foreach ($equipes as $equipe) { ?>
                  <option value="<?= $equipe['IDEQUIPE'] ?>"><?= $equipe['nomeFantasiaEquipe'] . ' - ' . $equipe['nomeEquipe'] ?></option>

                <?php } ?>
              </select>

            </div>
          </div>

          <hr class="my-4">

          <button class="w-100 btn btn-primary btn-lg" type="submit">Continue to checkout</button>
        </form>
      </div>
    </div>
  </main>