<!doctype html>
<html lang="en" data-bs-theme="auto">

<head>
    <script src="./assets/js/color-modes.js"></script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.122.0">
    <title>Sistema de Gestão de Atletas</title>

    <link rel="stylesheet" href="./css/styles.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@docsearch/css@3">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">

    <!-- CDN para o Bootstrap  -->
    <link href="./assets/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="./assets/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Mascara de entrada -->
    <script src="./assets/js/vanilla-masker.min.js"></script>

</head>
<?php
require_once './assets/php/common.php';
?>

<body>
    <div class="container py-3">
        <header>
            <div class="d-flex flex-column flex-md-row pb-3 mb-4 border-bottom">
                <a href="/" class="d-flex align-items-center link-body-emphasis text-decoration-none">
                    <img src="./images/swim_icon.png" sizes="32x32" height="32" alt="" style="padding-right: 20px;">
                    <span class="fs-4">Sistema de Gestão de Atletas</span>
                </a>
                <hr class="mb-0">
                <nav class="d-flex flex-column text-center flex-md-row mt-2 mt-md-0 ms-md-auto">
                    <?php if (isset($_SESSION['id']) && $_SESSION['permissao'] == 2) { ?>
                        <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="/select_atleta">Dados Atleta</a>
                    <?php } elseif (isset($_SESSION['id']) && $_SESSION['permissao'] == 1) { ?>
                        <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="/index_atleta?id=<?= $_SESSION['user_id'] ?>">Dados Atleta</a>
                    <?php } ?>
                    <hr>
                    <a class="me-3 py-2 link-body-emphasis text-decoration-none dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Tempos</a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="./list_indices">Índices</a></li>
                        <li><a class="dropdown-item" href="./list_recordes">Recordes</a></li>
                        <li><a class="dropdown-item" href="./tempos_atleta">Tempos do Atleta</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="/create_graph">Gráficos</a></li>
                    </ul>
                    <hr>
                    <a class="me-3 py-2 link-body-emphasis text-decoration-none nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Cadastros
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="./list_provas">Provas</a></li>
                        <li><a class="dropdown-item" href="./list_torneios">Torneios</a></li>
                        <li><a class="dropdown-item" href="./list_complexos">Piscinas</a></li>
                        <li><a class="dropdown-item" href="./list_equipes">Equipes</a></li>
                        <li><a class="dropdown-item" href="./list_federacao">Federações</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                    <hr>
                    <a class="me-3 py-2 link-body-emphasis text-decoration-none mb-3 mb-md-0" href="#">Agenda</a>
                    <?php if (isset($_SESSION['id']) && $_SESSION['permissao'] == 2) { ?>
                        <a class="me-md-3 mb-3 mb-md-0 py-2 btn btn-primary text-decoration-none" style="max-height: 40px" href="./index_admin">Admin</a>
                    <?php } ?>
                    <?php if (!isset($_SESSION['id'])) { ?>
                        <a class="py-2 btn btn-primary text-decoration-none" style="max-height: 40px" href="./sign_in">Entrar</a>
                    <?php } else { ?>
                        <a class="py-2 btn btn-primary text-decoration-none" style="max-height: 40px" href="./log_out">Sair</a>
                    <?php } ?>

                </nav>
            </div>

            <?php $this->content() ?>

            <footer class="pt-4 my-md-5 pt-md-5 border-top">
                <div class="row">
                    <div class="col-12 col-md">
                        <img class="mb-2" src="./images/swim_icon.png" alt="" width="24" height="19">
                        <small class="d-block mb-3 text-body-secondary">&copy; 2017–2024</small>
                    </div>
                    <div class="col-6 col-md">
                        <h5>Features</h5>
                        <ul class="list-unstyled text-small">
                            <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Cool stuff</a></li>
                            <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Random feature</a></li>
                            <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Team feature</a></li>
                            <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Stuff for developers</a></li>
                            <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Another one</a></li>
                            <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Last time</a></li>
                        </ul>
                    </div>
                    <div class="col-6 col-md">
                        <h5>Resources</h5>
                        <ul class="list-unstyled text-small">
                            <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Resource</a></li>
                            <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Resource name</a></li>
                            <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Another resource</a></li>
                            <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Final resource</a></li>
                        </ul>
                    </div>
                    <div class="col-6 col-md">
                        <h5>About</h5>
                        <ul class="list-unstyled text-small">
                            <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Team</a></li>
                            <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Locations</a></li>
                            <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Privacy</a></li>
                            <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Terms</a></li>
                        </ul>
                    </div>
                </div>
            </footer>
    </div>

    <?php //if ($_SERVER['REQUEST_URI'] == "/index_atleta") {
//        echo "<script>";
//        echo "const carousel25 = new bootstrap.Carousel('#carousel25');";
//        echo "const carousel50 = new bootstrap.Carousel('#carousel50');";
//        echo "</script>";
//    }
//    ?>

</body>

</html>
