<?php

$distanciaEstilo = $this->viewData->distanciaEstilo;
$torneios = $this->viewData->torneios;
$categorias = $this->viewData->categorias;
$provas = $this->viewData->provas;
$tempoAtleta = $this->viewData->tempoAtleta;
$indices = $this->viewData->indices;
$atleta = $this->viewData->atleta;

$torneiosParticipados = $this->viewData->torneiosParticipados;
$anos = $this->viewData->anos;
$estilos = $this->viewData->estilos;

// print_r($atleta);
// echo '<pre>';
// print_r($tempoAtleta);
// echo '</pre>';
function adjustTime($fullTime)
{
    $time = explode(':', $fullTime);
    (array_shift($time));
    return implode(':', $time);
}

?>

<main>
    <section class="py-5 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
                <h1 class="fw-light">Tempos Registrados</h1>
            </div>
        </div>
    </section>
    <div class="d-flex justify-content-end mb-5">
        <a class="btn btn-primary" href="./add_tempo">Incluir Tempo</a>
    </div>

    <div class="row p-3 ">
        <form action="graficos_tempo_filtrado" method="post" class="row g-3 d-flex align-items-end">
            <div class="col-md-4 col-lg-2">
                <label for="anoTempo" class="form-label">Ano</label>
                <select name="anoTempo" class="form-select" id="anoTempo">
                    <option value="">Selecione</option>
                    <?php foreach ($anos as $ano) { ?>
                        <option value="<?= $ano ?>"><?= $ano ?></option>
                    <?php }; ?>
                </select>
            </div>
            <div class="col-md-4 col-lg-2">
                <label for="nomeTorneio" class="form-label">Torneio</label>
                <select name="nomeTorneio" class="form-select" id="nomeTorneio">
                    <option value="">Selecione</option>
                    <?php foreach ($torneiosParticipados as $torneio) { ?>
                        <option value="<?= $torneio ?>"><?= $torneio ?></option>
                    <?php }; ?>
                </select>
            </div>
            <div class="col-md-4 col-lg-2">
                <label for="tamanhoPiscina" class="form-label">Piscina</label>
                <select name="tamanhoPiscina" class="form-select" id="tamanhoPiscina">
                    <option value="">Selecione</option>
                    <option value="25">25 m</option>
                    <option value="50">50 m</option>
                </select>
            </div>
            <div class="col-md-4 col-lg-2">
                <label for="distanciaEstilo" class="form-label">Estilo</label>
                <select name="distanciaEstilo" class="form-select" id="distanciaEstilo">
                    <option value="">Selecione</option>
                    <?php foreach ($estilos as $estilo) { ?>
                        <option value="<?php echo (explode('*', $estilo))[1] ?>"><?php echo (explode('*', $estilo))[0]  ?></option>
                    <?php }; ?>
                </select>
            </div>
            <div class="col-md-4 col-lg-2">
                <input type="submit" class="form-control btn btn-primary" value="Filtrar" id="filtrar">
            </div>
        </form>
    </div>

    <div>
        <canvas class="my-4 w-100" id="myChart" width="900" height="380"></canvas>
    </div>

    <div class="table-responsive">
        <table class="table text-center">
            <thead>
                <tr>
                    <th style="width: 12%;">Data</th>
                    <th style="width: 32%;">Torneio</th>
                    <th style="width: 22%;">Piscina</th>
                    <th style="width: 12%;">Estilo</th>
                    <th style="width: 22%;">Tempo</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($tempoAtleta as $tempo) { ?>
                    <tr>
                        <td><?php echo implode('/',  array_reverse(explode('-', $tempo['dataTorneio']))) ?></td>
                        <td><?= $tempo['nomeTorneio'] ?></td>
                        <td><?= $tempo['tamanhoPiscina'] . 'm' ?></td>
                        <td class="text-start"><?= $tempo['distancia'] . 'm ' . $tempo['nomeEstilo'] ?></td>
                        <td class="tempos"><?php echo adjustTime($tempo['tempoAtleta']) ?></td>
                        <td class="indices" hidden><?php if (!empty($tempo['tempoIndice'])) {
                                                        echo adjustTime($tempo['tempoIndice']);
                                                    } else {
                                                        echo '00:00.00';
                                                    } ?></td>
                    </tr>
                <?php } ?>
            </tbody>
        </table>
    </div>

</main>

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

<script>
    const ctx = document.getElementById('myChart');
    let times = document.getElementsByClassName('tempos');
    let indices = document.getElementsByClassName('indices');
    let timeArray = [];
    let labelTempos = [];
    let indiceArray = [];
    let labelIndices = [];

    for (let i = 0; i < times.length; i++) {
        let timeConverted = adjustTime(times[i].innerHTML);
        labelTempos.push(times[i].innerHTML);
        timeArray.push(timeConverted);
        let indiceConverted = adjustTime(indices[i].innerHTML);
        labelIndices.push(indices[i].innerHTML);
        indiceArray.push(indiceConverted);
        console.log(indices[i].innerHTML);


        // console.log(indiceArray);
    }

    function adjustTime(time) {
        console.log(time);
        let min = time.split(':')[0];
        let sec = (time.split(':')[1]).split('.')[0];
        let ms = (time.split(':')[1].split('.')[1]);
        const d = new Date(0, 0, 0, 0, min, sec, ms);
        let convTime = ((d.getTime())) - 2209063000000;
        return convTime;
    }

    console.log(timeArray);
    console.log(indiceArray);
    new Chart(ctx, {
        data: {
            datasets: [{
                    type: 'line',
                    label: labelTempos,
                    data: timeArray,
                    borderWidth: 1,
                    order: 1
                },
                {
                    type: 'line',
                    label: labelIndices,
                    data: indiceArray,
                    borderWidth: 1,
                    order: 2
                }
            ],
            labels: labelTempos
        },

        options: {
            scales: {
                y: {
                    beginAtZero: false
                }
            }
        }
    });
</script>
