<?php

$anos = $this->viewData->anos;
$estilos = $this->viewData->estilos;
$distanciaEstilo = $this->viewData->distanciaEstilo;
$torneios = $this->viewData->torneios;
$categorias = $this->viewData->categorias;
$provas = $this->viewData->provas;
$indicesMundial = $this->viewData->indices_mundial;
$tempoAtleta = $this->viewData->tempoAtleta;
$torneiosParticipados = $this->viewData->torneiosParticipados;

$arr_estilo = [];
foreach ($estilos as $estilo) {
   array_push($arr_estilo, explode('*', $estilo)[1]);
}

$arr_tempos = [];
for($i = 0; $i < count($arr_estilo); $i++ ) {
    $arr_tempo = [];
    foreach($tempoAtleta as $tempo) {
        if($tempo['distanciaEstilo'] == $arr_estilo[$i]) {
            $arr_tempo_data = [$tempo['dataTorneio'] => [$tempo['tempoAtleta'], $tempo['tamanhoPiscina']]];
            $arr_tempo += $arr_tempo_data;
        }
        $arr_estilo_tempo = [$arr_estilo[$i] => $arr_tempo];
    }
    $arr_tempos += $arr_estilo_tempo;
}
function diferencaTempoAnterior($estilo, $tempo, $data, $piscina, $arrUltimosTempos){
    foreach($arrUltimosTempos as $est => $values) {
        if ($estilo == $est) {
            $ultimosTempos = [];
            foreach($values as $date => $time) {
                if(date($data) > date($date) && $piscina == $time[1]) {
                    array_push($ultimosTempos, tempoEmSegundos(adjustTime($time[0])));
                }
            }
        }
    }
    if(!empty($ultimosTempos[0])) {
        return round((tempoEmSegundos(adjustTime($tempo)) - $ultimosTempos[0]),2);
    } else {
        return round(tempoEmSegundos(adjustTime($tempo)),2) * -1;
    }
}

?>

<main>
    <section class="py-5 text-center container">
        <div class="row py-lg-3">
            <div class="col-lg-6 col-md-8 mx-auto mb-3 mb-sm-1">
                <h1 class="fw-light">Tempos Registrados</h1>
            </div>
        </div>    
        <div class="d-none d-sm-flex justify-content-end mb-5">
            <a class="btn btn-primary" href="./add_tempo">Incluir Tempo</a>
        </div>
        <div class="d-flex d-sm-none justify-content-end mb-5">
            <a class="btn btn-primary w-100" href="./add_tempo">Incluir Tempo</a>
        </div>
        <div class="row p-3 ">
            <form action="filtra_tempos" method="post" class="row g-3 d-flex align-items-end">
                <div class="col-md-4 col-lg-2">
                    <label for="anoTempo" class="form-label">Ano</label>
                    <select name="anoTempo" class="form-select" id="anoTempo">
                        <option value="">Selecione</option>
                        <?php foreach ($anos as $ano) { ?>
                            <option value="<?= $ano ?>"><?= $ano ?></option>
                        <?php } ?>
                    </select>
                </div>
                <div class="col-md-4 col-lg-2">
                    <label for="nomeTorneio" class="form-label">Torneio</label>
                    <select name="nomeTorneio" class="form-select" id="nomeTorneio">
                        <option value="">Selecione</option>
                        <?php foreach ($torneiosParticipados as $torneio) { ?>
                            <option value="<?= $torneio ?>"><?= $torneio ?></option>
                        <?php } ?>
                    </select>
                </div>
                <div class="col-md-4 col-lg-2">
                    <label for="tamanhoPiscina" class="form-label">Piscina</label>
                    <select name="tamanhoPiscina" class="form-select" id="tamanhoPiscina">
                        <option value="">Selecione</option>
r                        <option value="25">25 m</option>
                        <option value="50">50 m</option>
                    </select>
                </div>
                <div class="col-md-4 col-lg-2">
                    <label for="distanciaEstilo" class="form-label">Estilo</label>
                    <select name="distanciaEstilo" class="form-select" id="distanciaEstilo">
                        <option value="">Selecione</option>
                        <?php foreach ($estilos as $estilo) { ?>
                            <option value="<?php echo (explode('*', $estilo))[1] ?>"><?php echo (explode('*', $estilo))[0]  ?></option>
                        <?php } ?>
                    </select>
                </div>
                <div class="col-md-4 col-lg-2">
                    <input type="submit" class="form-control btn btn-primary" value="Filtrar" id="filtrar">
                </div>
            </form>
        </div>
    
        
            <div class="table-responsive">
                <table class="table text-center">
                    <thead>
                        <tr>
                            <th>Data</th>
                            <th>Torneio</th>
                            <th>Piscina</th>
                            <th>Estilo</th>
                            <th>Tempo</th>
                            <th>IT</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($tempoAtleta as $tempo) { ?>
                            <tr>
                                <td><?php echo implode('/',  array_reverse(explode('-', $tempo['dataTorneio']))) ?></td>
                                <td><?= $tempo['nomeTorneio'] ?></td>
                                <td><?= $tempo['tamanhoPiscina'] . 'm' ?></td>
                                <td class="text-start"><?= $tempo['distancia'] . 'm ' . $tempo['nomeEstilo'] ?><?php if ($tempo['final'] == 'S') { ?><span class="badge text-bg-secondary ms-2">Final</span> <?php } ?> </td>
                                <?php $diferencaTempo = tempoEmMinutos(diferencaTempoAnterior($tempo['distanciaEstilo'], $tempo['tempoAtleta'], $tempo['dataTorneio'], $tempo['tamanhoPiscina'],$arr_tempos ));?>
                                <td><?php echo adjustTime($tempo['tempoAtleta']) ?> <span class="badge text-bg-<?php echo ($diferencaTempo > 0 ? 'danger': 'success') ?>"><?= $diferencaTempo?></span></td>
                                <td><?php echo indiceTecnico(adjustTime($tempo['tempoAtleta']), $tempo['distanciaEstilo'], $indicesMundial, $tempo['genero']) ?></td>
                                <td>
                                    <a href="edit_tempo?id=<?= $tempo['IDTMPATLETA'] ?>" class="btn btn-outline-primary">Editar</a>
                                </td>
                                <td>    
                                    <button type="button" class="btn btn-danger modalSelectBtn" data-bs-toggle="modal" data-bs-target="#exampleModal" value="<?= $tempo['IDTMPATLETA'] ?>">
                                        Delete
                                    </button>
                                </td>
                           </tr>
                        <?php } ?>
                    </tbody>
                </table>
            </div>
            
    </section>
</main>
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Modal title</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <span><input type="checkbox" id="confirmDelete" class="form-check-input"></span>
                Confirma exclusão do tempo?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <a href="#" id="deleteBtn" class="btn btn-danger disabled">Confirmar</a>
            </div>
        </div>
    </div>
</div>
<script>
    let buttons = document.getElementsByClassName('modalSelectBtn');
    let enableDelete = document.getElementById('confirmDelete');
    let deleteBtn = document.getElementById('deleteBtn');
    let hrefDeleteLink = ""

    for(let btn of buttons){
        btn.addEventListener('click', (e)=>{
            deleteBtn.classList.add('disabled');
            enableDelete.checked = false;
            hrefDeleteLink = "/delete_tempo?id=" + btn.value;
            deleteBtn.href = hrefDeleteLink;
        })
    }
    enableDelete.addEventListener('change', (e)=> {
        if(enableDelete.checked === true) {
            deleteBtn.classList.remove('disabled');
        } else {
            deleteBtn.classList.add('disabled');
        }
    })
</script>
