<?php

$anos = $this->viewData->anos;
$estilos = $this->viewData->estilos;
$distanciaEstilo = $this->viewData->distanciaEstilo;
$torneios = $this->viewData->torneios;
$categorias = $this->viewData->categorias;
$provas = $this->viewData->provas;
$indicesMundial = $this->viewData->indices_mundial;

$tempoAtleta = $this->viewData->tempoAtleta;
$torneiosParticipados = $this->viewData->torneiosParticipados;

//function indiceTecnico($tempo, $id_distanciaestilo, $indicesMundial, $genero)
//{
//    $tempoAtleta = tempoEmSegundos($tempo);
//    $tempoIndice = 0;
//    foreach ($indicesMundial as $indice) {
//        if ($indice['ID_DISTANCIAESTILO'] == $id_distanciaestilo && $indice['generoRecorde'] == $genero) {
//            $tempo = adjustTime($indice['tempoRecorde']);
//            $tempoIndice = tempoEmSegundos($tempo);
//        }
//    }
//    $indiceTecnico = 1000 * pow(($tempoIndice / $tempoAtleta), 3);
//
//    return floor($indiceTecnico);
//}

?>

<style>
    
    .grafico-circular {
        width: 10em;
        margin: 10px;
        justify-content: space-around;
    }

    .circulo {
        fill: none;
        stroke: #CCCCCC;
        stroke-width: 4px;
    }

    .circulo-progresso {
        fill: none;
        stroke-width: 4px;
        animation: progress 1s ease-out forwards;
        stroke: #22BF66;
    }

    @keyframes progress {
        0% {
            stroke-dasharray: 0 100;
        }
    }

    .label {
        fill: #343F4B;
        font-size: 0.2em;
        text-transform: uppercase;
        text-anchor: middle;
    }

    .label.percentage {
        font-size: 0.5em;
    }
</style>

<main>
    <section class="py-5 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
                <h1 class="fw-light">Tempos Registrados</h1>
            </div>
        </div>    
        <div class="d-flex justify-content-end mb-5">
            <a class="btn btn-primary" href="./add_tempo">Incluir Tempo</a>
        </div>
        <div class="row p-3 ">
            <form action="filtra_tempos" method="post" class="row g-3 d-flex align-items-end">
                <div class="col-md-4 col-lg-2">
                    <label for="anoTempo" class="form-label">Ano</label>
                    <select name="anoTempo" class="form-select" id="anoTempo">
                        <option value="">Selecione</option>
                        <?php foreach ($anos as $ano) { ?>
                            <option value="<?= $ano ?>"><?= $ano ?></option>
                        <?php } ?>
                    </select>
                </div>
                <div class="col-md-4 col-lg-2">
                    <label for="nomeTorneio" class="form-label">Torneio</label>
                    <select name="nomeTorneio" class="form-select" id="nomeTorneio">
                        <option value="">Selecione</option>
                        <?php foreach ($torneiosParticipados as $torneio) { ?>
                            <option value="<?= $torneio ?>"><?= $torneio ?></option>
                        <?php } ?>
                    </select>
                </div>
                <div class="col-md-4 col-lg-2">
                    <label for="tamanhoPiscina" class="form-label">Piscina</label>
                    <select name="tamanhoPiscina" class="form-select" id="tamanhoPiscina">
                        <option value="">Selecione</option>
                        <option value="25">25 m</option>
                        <option value="50">50 m</option>
                    </select>
                </div>
                <div class="col-md-4 col-lg-2">
                    <label for="distanciaEstilo" class="form-label">Estilo</label>
                    <select name="distanciaEstilo" class="form-select" id="distanciaEstilo">
                        <option value="">Selecione</option>
                        <?php foreach ($estilos as $estilo) { ?>
                            <option value="<?php echo (explode('*', $estilo))[1] ?>"><?php echo (explode('*', $estilo))[0]  ?></option>
                        <?php } ?>
                    </select>
                </div>
                <div class="col-md-4 col-lg-2">
                    <input type="submit" class="form-control btn btn-primary" value="Filtrar" id="filtrar">
                </div>
            </form>
        </div>
    
        
            <div class="table-responsive">
                <table class="table text-center">
                    <thead>
                        <tr>
                            <th>Data</th>
                            <th>Torneio</th>
                            <th>Piscina</th>
                            <th>Estilo</th>
                            <th>Tempo</th>
                            <th>IT</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($tempoAtleta as $tempo) { ?>
                            <tr>
                                <td><?php echo implode('/',  array_reverse(explode('-', $tempo['dataTorneio']))) ?></td>
                                <td><?= $tempo['nomeTorneio'] ?></td>
                                <td><?= $tempo['tamanhoPiscina'] . 'm' ?></td>
                                <td class="text-start"><?= $tempo['distancia'] . 'm ' . $tempo['nomeEstilo'] ?><?php if ($tempo['final'] == 'S') { ?><span class="badge text-bg-secondary ms-2">Final</span> <?php } ?> </td>
                                <td><?php echo adjustTime($tempo['tempoAtleta']) ?></td>
                                <td><?php echo indiceTecnico(adjustTime($tempo['tempoAtleta']), $tempo['distanciaEstilo'], $indicesMundial, $tempo['genero']) ?></td>
                                <td>
                                    <a href="edit_tempo?id=<?= $tempo['IDTMPATLETA'] ?>" class="btn btn-outline-primary">Editar</a>
                                </td>
                                <td>    
                                    <button type="button" class="btn btn-danger modalSelectBtn" data-bs-toggle="modal" data-bs-target="#exampleModal" value="<?= $tempo['IDTMPATLETA'] ?>">
                                        Delete
                                    </button>
                                </td>
                           </tr>
                        <?php } ?>
                    </tbody>
                </table>
            </div>
            
    </section>
</main>
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Modal title</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <span><input type="checkbox" id="confirmDelete" class="form-check-input"></span>
                Confirma exclusão do tempo?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <a href="#" id="deleteBtn" class="btn btn-danger disabled">Confirmar</a>
            </div>
        </div>
    </div>
</div>
<script>
    let buttons = document.getElementsByClassName('modalSelectBtn');
    let enableDelete = document.getElementById('confirmDelete');
    let deleteBtn = document.getElementById('deleteBtn');
    let hrefDeleteLink = ""

    for(let btn of buttons){
        btn.addEventListener('click', (e)=>{
            deleteBtn.classList.add('disabled');
            enableDelete.checked = false;
            hrefDeleteLink = "/delete_tempo?id=" + btn.value;
            deleteBtn.href = hrefDeleteLink;
        })
    }
    enableDelete.addEventListener('change', (e)=> {
        if(enableDelete.checked === true) {
            deleteBtn.classList.remove('disabled');
        } else {
            deleteBtn.classList.add('disabled');
        }
    })
</script>
