<?php

$recordes = $this->viewData->recordes;
//$anos = $this->viewData->anosIndice;
$tipos = $this->viewData->tipoRecorde;
$categorias = $this->viewData->categorias;
$piscinas = $this->viewData->piscinas;
$generos = ['F', 'M'];
$recordeSeparadoPorGenero = [];

foreach ($generos as $genero){
    $genero = array();
    foreach ($recordes as $recorde) {
        if ($recorde['generoRecorde'] == $genero) {
            array_push($genero, $recorde);
        }
    }
    print_r($genero);
} 


 echo "<pre>";
 print_r($recordeSeparadoPorGenero);
// print_r($anos);
// print_r($tipos);
// print_r($piscinas);
// echo '<br>';
// var_dump(array_search('2024', array_column($indices, 'anoIndice')));
 echo '</pre>';
?>


<main>
    <div class="py-5 text-center">
        <h2 class="fw-light">Tabela de Recordes</h2>
        <p class="lead"></p>
    </div>

    <?php $countIndices = 1 ?>
    <div class="table-responsive small indices-table">
        <?php foreach ($tipos as $tipo) { ?>
        <?php if ((array_search($tipo, array_column($recordes, 'tipoRecorde'))) !== false) { ?>
                <h3><?= $tipo ?></h3>
        <?php foreach ($generos as $genero) { ?>
            <?php if ((array_search($genero, array_column($recordes, 'generoRecorde'))) !== false) { ?>
                <h4><?= $genero ?></h4>
                    <table class="table table-sm mx-auto" id="indices-<?= $countIndices ?>">
                        <thead>
                            <tr>
                                <th scope="col">Prova</th>
                                <th scope="col">Genero</th>
                                <th scope="col">Categoria</th>
                                <th scope="col">Tempo</th>
                            </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($recordes as $recorde) {
                            if ($recorde['tipoRecorde'] == $tipo && $recorde['generoRecorde'] == $genero) {
                        ?>
                                <tr class="mb-1">
                                    <th class="col-sm-3 p-2" style=""><?= $recorde['distancia'] . 'm ' . $recorde['nomeEstilo'] ?></th>
                                    <td class="col-sm-2 p-2" style=""><?= $recorde['generoRecorde'] ?></td>
                                    <td class="col-sm-3 p-2" style=""><?php echo $recorde['nomeCategoria'] == 'Senior' ? 'Absoluto' : $recorde['nomeCategoria'] ?></td>
                                    <td class="col-sm-3 p-2" style=""><?= adjustTime($recorde['tempoRecorde']) ?></td>
                                </tr>
                        <?php }
                        } ?>
                        </tbody>
                    </table>
                    <?php $countIndices++ ?>
        <?php } ?>
        <?php } ?>
        <?php } ?>
        <?php } ?>
        <hr>
    </div>
</main>
