<?php
$federacoes = $this->viewData->federacoes;
$voltar = $_SERVER['HTTP_REFERER'];
?>

<div class="container">
    <main>
        <div class="py-5 text-center">
            <h2>Dados da Equipe</h2>
            <p class="lead">Incluir nova equipe</p>
        </div>
        <?php if (isset($_GET['error']) && $_GET['error'] == '3') {
            echo '<div class="alert alert-danger" role="alert">
                    Nome já cadastrado
                </div>';
        } elseif (isset($_GET['error']) && $_GET['error'] == '4') {
            echo '<div class="alert alert-danger" role="alert">
                    Sigla já cadastrada
                </div>';
        } ?>

        <div class="row g-5">
            <div class="col-md-5 col-lg-4 order-md-last">
                <div class="d-flex justify-content-center align-items-center mb-3">
                    <img class="img-logo-border" src="#" class="img-foto-border" alt="">
                </div>
                
            </div>
            <div class="col-md-7 col-lg-8">
                <h4 class="mb-3"></h4>
                <form action="/save_equipe" class="needs-validation" method="post" enctype="multipart/form-data">
                    <div class="row g-3">
                        <div class="col-12">
                            <label for="nomeEquipe" class="form-label">Nome</label>
                            <?php if (isset($_GET['error']) && $_GET['error'] == '1') {
                                echo '<div class="alert alert-danger" role="alert">
                                        Campo Obrigatório
                                     </div>';
                            } ?>
                            <input type="text" class="form-control" id="nomeEquipe" placeholder="Nome da Equipe" name="nomeEquipe" value="" required>
                        </div>
                        <div class="col-12">
                            <label for="nomeFantasiaEquipe" class="form-label">Sigla</label>
                            <input type="text" class="form-control" id="nomeFantasiaEquipe" placeholder="Sigla ou nome " name="nomeFantasiaEquipe" value="">
                        </div>
                    </div>

                    <div class="col-12">
                        <label for="emailEquipe" class="form-label">Email</label>
                        <input type="email" class="form-control" id="emailEquipe" placeholder="you@example.com" name="emailEquipe" value="">
                    </div>

                    <div class="col-12">
                        <label for="address" class="form-label">Site</label>
                        <input type="text" class="form-control" id="address" placeholder="www.example.com" name="siteEquipe">
                    </div>
                    <div class="row g-3">
                        <div class="col-6">
                            <label for="facebookEquipe" class="form-label">Facebook <span class="text-body-secondary">(Opcional)</span></label>
                            <input type="text" class="form-control" id="facebookEquipe" placeholder="Link facebook" name="facebookEquipe">
                        </div>
                        <div class="col-6">
                            <label for="instagramEquipe" class="form-label">Instagram <span class="text-body-secondary">(Opcional)</span></label>
                            <input type="text" class="form-control" id="instagramEquipe" placeholder="Link Instagram" name="instagramEquipe">
                        </div>
                    </div>

                    <div class="col-md-5">
                        <label for="telefoneEquipe" class="form-label">Telefone<span class="text-body-secondary">(Opcional)</span></label>
                        <input type="text" class="form-control" id="telefoneEquipe" placeholder="" name="telefoneEquipe">
                    </div>
                    <div class="row gy-3">
                        <div class="col-md-6">
                            <label for="logoEquipe" class="form-label">Logotipo</label>
                            <input type="file" class="form-control" id="logoEquipe" aria-describedby="inputGroupFileAddon04" aria-label="Upload" name="logoEquipe" accept="image/jpeg,.gif,.png">
                        </div>
                        <div class="col-md-6">
                            <label for="federacao" class="form-label">Federação</label>
                            <select name="id_federacao" class="form-select" id="federacao">
                                <option value="">Selecione</option>
                                <?php foreach ($federacoes as $federacao) { ?>
                                    <option value="<?= $federacao['IDFEDERACAO'] ?>"><?= $federacao['nomeFederacao'] ?></option>
                                <?php }; ?>
                            </select>
                        </div>
                    </div>
                    <hr class="my-4">
                    <div class="d-flex justify-content-around">
                        <button class="w-25 btn btn-primary btn-lg" type="submit">Incluir</button>
                        <a href="<?= $_SERVER['HTTP_REFERER'] ?>" class="w-25 btn btn-secondary btn-lg">Voltar</a>
                    </div>
                </form>
            </div>
        </div>
    </main>

    <script>
        // Função de máscara para telefone
        let telefone = document.querySelector('#telefoneEquipe');
        telefone.addEventListener('keypress', (event) => {
            if ((telefone.value).length < 16) {
                VMasker(telefone).maskPattern('(99) 9999 - 99999 ');
            } else {
                VMasker(telefone).maskPattern('(99) 99999 - 9999 ');
            }
        });
    </script>
