<?php
// print_r($this->viewData->equipe);
$equipe = $this->viewData->equipe;
$federacoes = $this->viewData->federacoes;

$disabled = (isset($this->setHtmlData->edit) ? $this->setHtmlData->edit : 'disabled');
?>

<div class="container">
    <main>
        <div class="py-5 text-center">
            <h2>Dados da Equipe</h2>
            <p class="lead">Alteração dos dados</p>
        </div>

        <div class="row g-5">
            <div class="col-md-5 col-lg-4 order-md-last">
                <div class="d-flex justify-content-center align-items-center mb-3">
                    <img class="img-logo" src="<?= $equipe['logoEquipe'] ?>" class="img-foto" alt="">
                </div>
            </div>
            <div class="col-md-7 col-lg-8">
                <form action="update_equipe" method="POST" enctype="multipart/form-data" class="needs-validation" novalidate>
                    <div class="row g-3">
                        <div class="col-12">
                            <input type="hidden" name="idequipe" value="<?= $equipe['IDEQUIPE'] ?>">
                            <label for="firstName" class="form-label">Nome</label>
                            <input type="text" class="form-control" id="firstName" placeholder="Nome" name="nomeEquipe" value="<?= $equipe['nomeEquipe'] ?>" <?php if ($_SESSION['permissao'] != 2) echo 'readonly'; ?>>
                        </div>
                        <div class="col-12">
                            <label for="nickname" class="form-label">Sigla</label>
                            <input type="text" class="form-control" id="nickname" placeholder="Apelido" name="nomeFantasiaEquipe" value="<?= $equipe['nomeFantasiaEquipe'] ?>" <?php if ($_SESSION['permissao'] != 2) echo 'readonly'; ?>>
                        </div>
                    </div>

                    <div class="col-12">
                        <label for="email" class="form-label">Email</label>
                        <input type="email" class="form-control" id="email" placeholder="you@example.com" name="emailEquipe" value="<?= $equipe['emailEquipe'] ?>">
                    </div>

                    <div class="col-12">
                        <label for="address" class="form-label">Site</label>
                        <input type="text" class="form-control" id="address" placeholder="www.example.com" name="siteEquipe" value="<?= $equipe['siteEquipe'] ?>">
                    </div>
                    <div class="row g-3">
                        <div class="col-6">
                            <label for="facebook" class="form-label" name>Facebook <span class="text-body-secondary">(Opcional)</span></label>
                            <input type="text" class="form-control" id="facebook" name="facebookEquipe" placeholder="Link facebook" value="<?= $equipe['facebookEquipe'] ?>">
                        </div>
                        <div class="col-6">
                            <label for="instagram" class="form-label">Instagram <span class="text-body-secondary">(Opcional)</span></label>
                            <input type="text" class="form-control" id="instagram" name="instagramEquipe" placeholder="Link Instagram" value="<?= $equipe['instagramEquipe'] ?>">
                        </div>
                    </div>

                    <div class="col-md-5">
                        <label for="telefoneEquipe" class="form-label">Telefone<span class="text-body-secondary">(Opcional)</span></label>
                        <input type="phone" class="form-control" id="telefoneEquipe" name="telefoneEquipe" placeholder="" value="<?= $equipe['telefoneEquipe'] ?>">
                    </div>
                    <div class="row gy-3">
                        <div class="col-md-6">
                            <label for="logoEquipe" class="form-label">Logotipo</label>
                            <input type="file" class="form-control" id="logoEquipe" aria-describedby="inputGroupFileAddon04" aria-label="Upload" name="logoEquipe" accept="image/jpeg,.gif,.png" value="<?= $equipe['logoEquipe'] ?>">
                            <input type="hidden" name="logoAntiga" value="<?= $equipe['logoEquipe'] ?>">
                        </div>
                        <div class="col-md-6">
                            <label for="federacao" class="form-label">Federação</label>
                            <select name="id_federacao" class="form-select" id="federacao">
                                <option value="">Selecione</option>
                                <?php foreach ($federacoes as $federacao) { ?>
                                    <option value="<?= $federacao['IDFEDERACAO'] ?>" <?php if ($federacao['IDFEDERACAO'] == $equipe['ID_FEDERACAO']) {
                                                                                            echo 'selected';
                                                                                        } ?>><?= $federacao['nomeFederacao'] ?></option>
                                <?php } ?>
                            </select>
                        </div>
                    </div>
                    <hr class="my-4">
                    <div class="grid column-gap-0">

                        <button class="w-25 btn btn-primary btn-lg" type="submit">Edit</button>

                        <?php if ($_SESSION['permissao'] == 2) { ?>
                            <a class="w-25 btn btn-secondary btn-lg" href="/equipe_admin">Voltar</a>
                        <?php } else { ?>
                            <a class="w-25 btn btn-secondary btn-lg" href="/list_equipes">Voltar</a>
                        <?php } ?>
                    </div>
                </form>
            </div>
        </div>
    </main>
</div>

<script>
    let telefone = document.querySelector('#telefoneEquipe');

    telefone.addEventListener('keypress', (event) => {
        console.log((telefone.value).length);

        if ((telefone.value).length < 16) {
            VMasker(telefone).maskPattern('(99) 9999 - 99999 ');
            console.log(telefone.innerHTML);
        } else {
            VMasker(telefone).maskPattern('(99) 99999 - 9999 ');
            console.log(telefone.innerHTML);
        }
    });
    // })
</script>
