#Versao apache 0.1

FROM php:8.1-apache
WORKDIR /var/www/html/
# COPY . .
EXPOSE 80

# RUN chown -R www-data:www-data /var/www
# RUN chown -R www-data:www-data /var/www

COPY ./apache2.conf /etc/apache2

ENV APACHE_DOCUMENT_ROOT=/var/www/html/public/

RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf
RUN sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf

RUN apt-get update

ADD --chmod=0755 https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/

RUN install-php-extensions @composer
RUN install-php-extensions bcmath gd intl pdo_mysql

RUN a2enmod rewrite

