#Versao 0.0.1

FROM php:8.1-apache
WORKDIR /var/www/html/public/
COPY . .
EXPOSE 80

RUN chown -R www-data:www-data /var/www
# RUN chown -R www-data:www-data /var/www

COPY ./apache2.conf /etc/apache2

ENV APACHE_DOCUMENT_ROOT /var/www/html/public

RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf
RUN sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf

RUN apt-get update && apt-get install -y \
  libfreetype-dev \
  libjpeg62-turbo-dev \
  libpng-dev \
  vim
# php8.2-common \
# php8.2-mysql \
# php8.2-xml \
# php8.2-xmlrpc \
# php8.2-curl \
# php8.2-gd \
# php8.2-imagick \
# php8.2-cli \
# php8.2-fpm \
# php8.2-dev \
# php8.2-imap \
# php8.2-mbstring \
# php8.2-opcache \
# php8.2-soap \
# php8.2-zip \
# php8.2-redis \
# php8.2-intl 

RUN docker-php-ext-install pdo pdo_mysql 
