#Versao nginx 0.0.1

FROM php:8.1-apache
WORKDIR /var/www/html/
COPY . .
EXPOSE 80

# RUN chown -R www-data:www-data /var/www
# RUN chown -R www-data:www-data /var/www

COPY ./apache2.conf /etc/apache2

ENV APACHE_DOCUMENT_ROOT /var/www/html/public/

# RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf
# RUN sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf
RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf
RUN sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf


RUN apt-get update

ADD --chmod=0755 https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/

RUN install-php-extensions @composer
RUN install-php-extensions bcmath gd intl pdo_mysql

RUN a2enmod rewrite

# RUN composer install
# libfreetype-dev \
# libjpeg62-turbo-dev \
# libpng-dev \
# php8.1 \
# php8.1-common \
# php8.1-mysql \
# php8.1-xml \
# php8.1-xmlrpc \
# php8.1-curl \
# php8.1-gd \
# php8.1-imagick \
# php8.1-cli \
# php8.1-fpm \
# php8.1-dev \
# php8.1-imap \
# php8.1-mbstring \
# php8.1-opcache \
# php8.1-soap \
# php8.1-zip \
# php8.1-redis \
# php8.1-intl \
# vim
