<?php

?>

<header class="">
    <div class="pricing-header pb-md-4 mx-auto text-center">
        <img src="./images/capa_index.jpeg" class="img-index img-fluid mb-5" alt="">
        <h1 class="display-3 fw-light text-body-emphasis mb-3">Sistema de Gestão de Atletas de Natação</h1>
        <p class=" display-6 text-body-secondary p-3">Controle os resultados e estatísticas dos atletas. Verifique as metas e compare com os tempos obtidos. Analise a evolução física.</p>
    </div>
</header>

<main>

    <h3 class="display-4 fw-light mb-5 text-center">
        Últimos Torneios
    </h3>
    <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
        <div class="col">
            <div class="card mb-4 rounded-3 shadow-sm">
                <div class="card-header py-3">
                    <h4 class="my-0 fw-normal">Prova principal 1</h4>
                </div>
                <div class="card-body">
                    <p>MELHOR TEMPO</p>
                    <h1 class="card-title pricing-card-title">00:00.00</h1>
                    <ul class="list-unstyled mt-3 mb-4">
                        <li>22/11/22</li>
                        <li>Torneio???</li>
                        <li>Piscina???</li>
                        <li>Local???</li>
                    </ul>
                    <button type="button" class="w-100 btn btn-lg btn-outline-primary">Sign up for free</button>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card mb-4 rounded-3 shadow-sm">
                <div class="card-header py-3">
                    <h4 class="my-0 fw-normal">Prova principal 2</h4>
                </div>
                <div class="card-body">
                    <p>MELHOR TEMPO</p>
                    <h1 class="card-title pricing-card-title">00:00.00</h1>
                    <ul class="list-unstyled mt-3 mb-4">
                        <li>20 users included</li>
                        <li>10 GB of storage</li>
                        <li>Priority email support</li>
                        <li>Help center access</li>
                    </ul>
                    <button type="button" class="w-100 btn btn-lg btn-primary">Get started</button>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card mb-4 rounded-3 shadow-sm border-primary">
                <div class="card-header py-3 text-bg-primary border-primary">
                    <h4 class="my-0 fw-normal">Prova principal 3</h4>
                </div>
                <div class="card-body">
                    <p>MELHOR TEMPO</p>
                    <h1 class="card-title pricing-card-title">00:00.00</h1>
                    <ul class="list-unstyled mt-3 mb-4">
                        <li>30 users included</li>
                        <li>15 GB of storage</li>
                        <li>Phone and email support</li>
                        <li>Help center access</li>
                    </ul>
                    <button type="button" class="w-100 btn btn-lg btn-primary">Contact us</button>
                </div>
            </div>
        </div>
    </div>

    <h2 class="display-6 text-center mb-4">Compare plans</h2>

    <div class="table-responsive">
        <table class="table text-center">
            <thead>
                <tr>
                    <th style="width: 34%;"></th>
                    <th style="width: 22%;">Free</th>
                    <th style="width: 22%;">Pro</th>
                    <th style="width: 22%;">Enterprise</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <th scope="row" class="text-start">Public</th>
                    <td><svg class="bi" width="24" height="24">
                            <use xlink:href="#check" />
                        </svg></td>
                    <td><svg class="bi" width="24" height="24">
                            <use xlink:href="#check" />
                        </svg></td>
                    <td><svg class="bi" width="24" height="24">
                            <use xlink:href="#check" />
                        </svg></td>
                </tr>
                <tr>
                    <th scope="row" class="text-start">Private</th>
                    <td></td>
                    <td><svg class="bi" width="24" height="24">
                            <use xlink:href="#check" />
                        </svg></td>
                    <td><svg class="bi" width="24" height="24">
                            <use xlink:href="#check" />
                        </svg></td>
                </tr>
            </tbody>

            <tbody>
                <tr>
                    <th scope="row" class="text-start">Permissions</th>
                    <td><svg class="bi" width="24" height="24">
                            <use xlink:href="#check" />
                        </svg></td>
                    <td><svg class="bi" width="24" height="24">
                            <use xlink:href="#check" />
                        </svg></td>
                    <td><svg class="bi" width="24" height="24">
                            <use xlink:href="#check" />
                        </svg></td>
                </tr>
                <tr>
                    <th scope="row" class="text-start">Sharing</th>
                    <td></td>
                    <td><svg class="bi" width="24" height="24">
                            <use xlink:href="#check" />
                        </svg></td>
                    <td><svg class="bi" width="24" height="24">
                            <use xlink:href="#check" />
                        </svg></td>
                </tr>
                <tr>
                    <th scope="row" class="text-start">Unlimited members</th>
                    <td></td>
                    <td><svg class="bi" width="24" height="24">
                            <use xlink:href="#check" />
                        </svg></td>
                    <td><svg class="bi" width="24" height="24">
                            <use xlink:href="#check" />
                        </svg></td>
                </tr>
                <tr>
                    <th scope="row" class="text-start">Extra security</th>
                    <td></td>
                    <td></td>
                    <td><svg class="bi" width="24" height="24">
                            <use xlink:href="#check" />
                        </svg></td>
                </tr>
            </tbody>
        </table>
    </div>
</main>
