<main class="form-signin w-100 m-auto">
    <div class="text-center">
        <img class="mb-4" src="./images/swim_icon.png" alt="" width="72" height="57">
        <h1 class="display-4 fw-light py-3 text-center">Cadastro</h1>
        <h3 class="lead py-3">Cadastre-se para ter acesso ao registro de atividades.</h3>

        <div class="form-floating mb-2">
            <a href="add_atleta" class="btn btn-secondary w-100 m-auto">Sou um atleta</a>
        </div>
        <div class="form-floating">
            <a href="add_atleta" class="btn btn-secondary w-100 m-auto">Sou técnico de uma equipe</a>
        </div>

        <!-- <div class="form-check text-start my-3">
      <input class="form-check-input" type="checkbox" value="remember-me" id="flexCheckDefault">
      <label class="form-check-label" for="flexCheckDefault">
        Remember me
      </label>
    </div> -->
        <!-- <button class="btn btn-primary w-100 py-2" type="submit">Entrar</button> -->
    </div>
    <!-- <a class="btn btn-primary w-100 py-2 mt-3" href="register">Não tenho cadastro</a> -->
    <p class="mt-5 mb-3 text-body-secondary">&copy; 2017–2024</p>
</main>
